In [1]:
import pandas as pd # type: ignore
import numpy as np
import matplotlib as plt  # type: ignore
import seaborn as sns # type: ignore
from sklearn.model_selection import train_test_split, GridSearchCV # type: ignore
from sklearn.metrics import mean_squared_error, r2_score # type: ignore
import os
import joblib # type: ignore
from sklearn.linear_model import Lasso

In [2]:
dr = pd.read_excel('descriptors.xlsx')
del dr['ID']
dr.head()

,smiles,vmin_vmin_boltz,vmin_r_boltz,fmo_e_homo_boltz,fmo_e_lumo_boltz,fmo_mu_boltz,fmo_eta_boltz,fmo_omega_boltz,somo_ra_boltz,somo_rc_boltz,...,sterimol_burB5_boltz,sterimol_burB5_min,sterimol_burB5_max,sterimol_burB5_delta,sterimol_burB5_vburminconf,sterimol_burL_boltz,sterimol_burL_min,sterimol_burL_max,sterimol_burL_delta,sterimol_burL_vburminconf
0,CC(C)c1cc(C(C)C)c(-c2ccccc2P(C2CCCCC2)C2CCCCC2...,-0.061654,1.819048,-0.218243,-0.025112,-0.121678,0.193131,0.038336,0.059115,-0.363712,...,7.439480,6.306577,7.835474,1.528897,7.262693,7.291573,7.106519,8.238802,1.132283,7.735548
1,CN(C)c1cccc(N(C)C)c1-c1ccccc1P(C1CCCCC1)C1CCCCC1,-0.063670,1.784157,-0.206310,-0.023277,-0.114794,0.183033,0.036033,0.061658,-0.345264,...,6.572514,6.339063,7.850955,1.511892,6.407769,7.285463,6.908743,8.216943,1.308200,7.992698
2,COc1cccc(OC)c1-c1ccccc1P(C1CCCCC1)C1CCCCC1,-0.066303,1.798595,-0.213323,-0.016923,-0.115123,0.196400,0.033750,0.069846,-0.356952,...,7.156276,6.349086,7.287324,0.938238,7.021625,7.306643,7.025374,8.361404,1.336030,7.424874
3,CC(C)Oc1cccc(OC(C)C)c1-c1ccccc1P(C1CCCCC1)C1CC...,-0.067319,1.795292,-0.211571,-0.013802,-0.112687,0.197770,0.032124,0.070775,-0.349017,...,7.238774,6.369287,7.813010,1.443723,7.653520,7.338674,6.996319,8.333428,1.337110,7.483233
4,c1ccc(-c2ccccc2P(C2CCCCC2)C2CCCCC2)cc1,-0.061351,1.816461,-0.218842,-0.030145,-0.124494,0.188697,0.041069,0.060353,-0.376125,...,6.497622,6.092458,7.055260,0.962802,6.376705,7.370445,7.021018,8.155038,1.134020,8.086289

In [3]:
df = pd.read_csv("Morgan.csv")
del df['ID']
df.head()

,smiles,morgan_fingerprint
0,CC(C)c1cc(C(C)C)c(-c2ccccc2P(C2CCCCC2)C2CCCCC2...,0110100000000000000000000000000101000000000001...
1,CN(C)c1cccc(N(C)C)c1-c1ccccc1P(C1CCCCC1)C1CCCCC1,0010100000000001000000000000000101000000000001...
2,COc1cccc(OC)c1-c1ccccc1P(C1CCCCC1)C1CCCCC1,0010100000000001000000000000001101000000000001...
3,CC(C)Oc1cccc(OC(C)C)c1-c1ccccc1P(C1CCCCC1)C1CC...,0110100000000001000000000000001101000000000001...
4,c1ccc(-c2ccccc2P(C2CCCCC2)C2CCCCC2)cc1,0010100000000000000000000000000100000000000001...

In [4]:
def split_bits(row):
    if pd.isna(row['morgan_fingerprint']):
        return pd.Series([np.nan] * 1024)
    else:
        return pd.Series(list(row['morgan_fingerprint']))

bit_columns = df.apply(split_bits, axis=1)

bit_columns.columns = [f'F_{i+1}' for i in range(bit_columns.shape[1])]
final_df = pd.concat([df.reset_index(drop=True), bit_columns], axis=1)
final_df.head()

,smiles,morgan_fingerprint,F_1,F_2,F_3,F_4,F_5,F_6,F_7,F_8,...,F_1015,F_1016,F_1017,F_1018,F_1019,F_1020,F_1021,F_1022,F_1023,F_1024
0,CC(C)c1cc(C(C)C)c(-c2ccccc2P(C2CCCCC2)C2CCCCC2...,0110100000000000000000000000000101000000000001...,0,1,1,0,1,0,0,0,...,0,0,0,0,0,1,0,0,0,0
1,CN(C)c1cccc(N(C)C)c1-c1ccccc1P(C1CCCCC1)C1CCCCC1,0010100000000001000000000000000101000000000001...,0,0,1,0,1,0,0,0,...,0,0,0,0,0,1,0,0,0,0
2,COc1cccc(OC)c1-c1ccccc1P(C1CCCCC1)C1CCCCC1,0010100000000001000000000000001101000000000001...,0,0,1,0,1,0,0,0,...,0,0,0,0,0,1,0,0,0,0
3,CC(C)Oc1cccc(OC(C)C)c1-c1ccccc1P(C1CCCCC1)C1CC...,0110100000000001000000000000001101000000000001...,0,1,1,0,1,0,0,0,...,0,0,0,0,0,1,0,0,0,0
4,c1ccc(-c2ccccc2P(C2CCCCC2)C2CCCCC2)cc1,0010100000000000000000000000000100000000000001...,0,0,1,0,1,0,0,0,...,0,0,0,0,0,1,0,0,0,0

In [5]:
final_df = final_df.dropna()

y1 = dr[dr['smiles'].isin(final_df['smiles'])]

In [6]:
input = final_df.copy()
del input['morgan_fingerprint']
del input['smiles']
input.head()

,F_1,F_2,F_3,F_4,F_5,F_6,F_7,F_8,F_9,F_10,...,F_1015,F_1016,F_1017,F_1018,F_1019,F_1020,F_1021,F_1022,F_1023,F_1024
0,0,1,1,0,1,0,0,0,0,0,...,0,0,0,0,0,1,0,0,0,0
1,0,0,1,0,1,0,0,0,0,0,...,0,0,0,0,0,1,0,0,0,0
2,0,0,1,0,1,0,0,0,0,0,...,0,0,0,0,0,1,0,0,0,0
3,0,1,1,0,1,0,0,0,0,0,...,0,0,0,0,0,1,0,0,0,0
4,0,0,1,0,1,0,0,0,0,0,...,0,0,0,0,0,1,0,0,0,0

In [7]:
del y1['smiles']

In [8]:
for column in input.columns:
    if input[column].dtype == 'object':
        input[column] = pd.to_numeric(input[column], errors='coerce')

# Check the new data types
print(input.dtypes)

F_1       int64
F_2       int64
F_3       int64
F_4       int64
F_5       int64
          ...
F_1020    int64
F_1021    int64
F_1022    int64
F_1023    int64
F_1024    int64
Length: 1024, dtype: object

In [9]:
import pandas as pd
from sklearn.preprocessing import StandardScaler
from sklearn.decomposition import PCA

In [10]:
n_components = 5

abb = y1

# Scale the features
scaler = StandardScaler()
X_scaled = scaler.fit_transform(abb)

#pca = PCA(n_components=n_components)
#X_pca = pca.fit_transform(X_scaled)

# Create a DataFrame for the PCA-transformed data
#pca_df = pd.DataFrame(X_pca, columns=[f'PC{i+1}' for i in range(n_components)])

# Save the PCA-transformed data to a new CSV file
#pca_df.to_csv('pca.csv', index=False)

print("Transformation complete. Transformed data saved to 'pca.csv'.")

Transformation complete. Transformed data saved to 'pca.csv'.

In [11]:
pip install optuna

Requirement already satisfied: optuna in d:\conda\lib\site-packages (4.0.0)
Requirement already satisfied: alembic>=1.5.0 in d:\conda\lib\site-packages (from optuna) (1.13.3)
Requirement already satisfied: colorlog in d:\conda\lib\site-packages (from optuna) (6.8.2)
Requirement already satisfied: numpy in d:\conda\lib\site-packages (from optuna) (1.26.4)
Requirement already satisfied: packaging>=20.0 in d:\conda\lib\site-packages (from optuna) (23.2)
Requirement already satisfied: sqlalchemy>=1.3.0 in d:\conda\lib\site-packages (from optuna) (2.0.30)
Requirement already satisfied: tqdm in d:\conda\lib\site-packages (from optuna) (4.66.4)
Requirement already satisfied: PyYAML in d:\conda\lib\site-packages (from optuna) (6.0.1)
Requirement already satisfied: Mako in d:\conda\lib\site-packages (from alembic>=1.5.0->optuna) (1.3.5)
Requirement already satisfied: typing-extensions>=4 in d:\conda\lib\site-packages (from alembic>=1.5.0->optuna) (4.11.0)
Requirement already satisfied: greenlet!=0.4.17 in d:\conda\lib\site-packages (from sqlalchemy>=1.3.0->optuna) (3.0.1)
Requirement already satisfied: colorama in d:\conda\lib\site-packages (from colorlog->optuna) (0.4.6)
Requirement already satisfied: MarkupSafe>=0.9.2 in d:\conda\lib\site-packages (from Mako->alembic>=1.5.0->optuna) (2.1.3)
Note: you may need to restart the kernel to use updated packages.

In [12]:
import logging
import os
import numpy as np
import pandas as pd
import tensorflow as tf
from tensorflow.keras.models import Sequential
from tensorflow.keras.layers import Dense, Dropout
from tensorflow.keras.optimizers import Adam
from sklearn.model_selection import train_test_split
from sklearn.metrics import mean_absolute_error, r2_score
import optuna
import joblib

In [13]:
from tensorflow.keras.layers import BatchNormalization

In [27]:
logging.basicConfig(level=logging.INFO, format='%(asctime)s - %(levelname)s - %(message)s')

X = input
Y = abb.copy()  
results_list = []
model_dir = 'models_dl_bayes_val_cv'
os.makedirs(model_dir, exist_ok=True)

# Function to create the model
def create_model(n_layers, n_units, dropout_rate, learning_rate, input_shape):
    model = Sequential()
    model.add(Dense(n_units, activation='relu', input_shape=(input_shape,)))
    model.add(BatchNormalization())
    
    for _ in range(n_layers - 1):
        model.add(Dense(n_units, activation='relu'))
        model.add(BatchNormalization())
        model.add(Dropout(dropout_rate))
    
    model.add(Dense(1))  # Output layer for regression

    model.compile(optimizer=Adam(learning_rate=learning_rate), loss='mean_absolute_error')
    return model

# Optuna objective function
def objective(trial, X_train, y_train, X_val, y_val):
    # Hyperparameters to tune
    n_layers = trial.suggest_int('n_layers', 1, 5)
    n_units = trial.suggest_int('n_units', 16, 256)
    dropout_rate = trial.suggest_float('dropout_rate', 0.0, 0.5)
    learning_rate = trial.suggest_loguniform('learning_rate', 1e-4, 1e-2)
    batch_size = trial.suggest_int('batch_size', 16, 128)

    # Create the model
    model = create_model(n_layers, n_units, dropout_rate, learning_rate, X_train.shape[1])

    # Train the model
    history = model.fit(X_train, y_train, 
                        validation_data=(X_val, y_val), 
                        epochs=100, batch_size=batch_size, 
                        verbose=0, callbacks=[tf.keras.callbacks.EarlyStopping(patience=5)])
    
    # Evaluate the model
    val_pred = model.predict(X_val)
    val_mae = mean_absolute_error(y_val, val_pred)

    return val_mae  # Minimize MAE

for feature in Y.columns:
    model_path = os.path.join(model_dir, f'model_{feature}.h5')

    # Skip if model already exists
    if os.path.exists(model_path):
        logging.info(f"Model for feature '{feature}' already exists, skipping...")
        continue

    y = Y[feature].to_numpy()  # Convert y to a NumPy array
    
    # Split the data into train, validation, and test sets
    X_train, X_temp, y_train, y_temp = train_test_split(X, y, test_size=0.4, random_state=42)
    X_val, X_test, y_val, y_test = train_test_split(X_temp, y_temp, test_size=0.5, random_state=42)

    # Ensure types are correct
    X_train = X_train.astype(np.float64)
    y_train = y_train.astype(np.float64)

    # Log shapes
    logging.info("Shapes for feature '%s': X_train: %s, y_train: %s", feature, X_train.shape, y_train.shape)

    # Create a study for Bayesian optimization
    study = optuna.create_study(direction='minimize')  # Minimize MAE
    try:
        study.optimize(lambda trial: objective(trial, X_train, y_train, X_val, y_val), n_trials=10)
    except Exception as e:
        logging.error(f"Error during optimization for feature '{feature}': {e}")
        continue
    
    best_params = study.best_params
    
    # Create the best model with optimized parameters
    best_model = create_model(
        best_params['n_layers'], 
        best_params['n_units'], 
        best_params['dropout_rate'], 
        best_params['learning_rate'], 
        X_train.shape[1]
    )
    
    # Fit the best model
    try:
        best_model.fit(X_train, y_train, 
                       validation_data=(X_val, y_val), 
                       epochs=100, batch_size=best_params['batch_size'], 
                       verbose=0, callbacks=[tf.keras.callbacks.EarlyStopping(patience=5)])
    except Exception as e:
        logging.error(f"Error during fitting of the best model for feature '{feature}': {e}")
        continue

    # Evaluate the model on validation and test sets
    val_pred = best_model.predict(X_val)
    val_mae = mean_absolute_error(y_val, val_pred)  # Validation MAE
    
    y_pred = best_model.predict(X_test)
    test_mae = mean_absolute_error(y_test, y_pred)  # Test MAE
    r2 = r2_score(y_test, y_pred)
    
    # Store the results
    results_list.append({
        'Feature': feature,
        'Validation MAE': val_mae,
        'Test MAE': test_mae,
        'R²': r2,
        'Best Parameters': best_params
    })
    
    # Save the model
    best_model.save(model_path)
    logging.info(f"Model for feature '{feature}' saved successfully.")

# Save all results to a CSV file
results_df = pd.DataFrame(results_list)
results_df.to_csv('model_performance_dl.csv', index=False)
logging.info("Best model performance metrics saved to 'model_performance_dl.csv'.")
logging.info("Best models saved in the 'models_dl_bayes_val_cv' directory.")

2024-09-26 19:06:11,074 - INFO - Model for feature 'vmin_vmin_boltz' already exists, skipping...
2024-09-26 19:06:11,077 - INFO - Model for feature 'vmin_r_boltz' already exists, skipping...
2024-09-26 19:06:11,080 - INFO - Model for feature 'fmo_e_homo_boltz' already exists, skipping...
2024-09-26 19:06:11,081 - INFO - Model for feature 'fmo_e_lumo_boltz' already exists, skipping...
2024-09-26 19:06:11,081 - INFO - Model for feature 'fmo_mu_boltz' already exists, skipping...
2024-09-26 19:06:11,081 - INFO - Model for feature 'fmo_eta_boltz' already exists, skipping...
2024-09-26 19:06:11,086 - INFO - Model for feature 'fmo_omega_boltz' already exists, skipping...
2024-09-26 19:06:11,087 - INFO - Model for feature 'somo_ra_boltz' already exists, skipping...
2024-09-26 19:06:11,090 - INFO - Model for feature 'somo_rc_boltz' already exists, skipping...
2024-09-26 19:06:11,091 - INFO - Model for feature 'nbo_P_boltz' already exists, skipping...
2024-09-26 19:06:11,093 - INFO - Model for feature 'nbo_P_ra_boltz' already exists, skipping...
2024-09-26 19:06:11,096 - INFO - Model for feature 'spindens_P_ra_boltz' already exists, skipping...
2024-09-26 19:06:11,098 - INFO - Model for feature 'nbo_P_rc_boltz' already exists, skipping...
2024-09-26 19:06:11,101 - INFO - Model for feature 'spindens_P_rc_boltz' already exists, skipping...
2024-09-26 19:06:11,102 - INFO - Model for feature 'nmr_P_boltz' already exists, skipping...
2024-09-26 19:06:11,103 - INFO - Model for feature 'nmrtens_sxx_P_boltz' already exists, skipping...
2024-09-26 19:06:11,104 - INFO - Model for feature 'nmrtens_syy_P_boltz' already exists, skipping...
2024-09-26 19:06:11,106 - INFO - Model for feature 'nmrtens_szz_P_boltz' already exists, skipping...
2024-09-26 19:06:11,108 - INFO - Model for feature 'efg_amp_P_boltz' already exists, skipping...
2024-09-26 19:06:11,111 - INFO - Model for feature 'efgtens_xx_P_boltz' already exists, skipping...
2024-09-26 19:06:11,111 - INFO - Model for feature 'efgtens_yy_P_boltz' already exists, skipping...
2024-09-26 19:06:11,111 - INFO - Model for feature 'efgtens_zz_P_boltz' already exists, skipping...
2024-09-26 19:06:11,117 - INFO - Model for feature 'nuesp_P_boltz' already exists, skipping...
2024-09-26 19:06:11,119 - INFO - Model for feature 'E_solv_cds_boltz' already exists, skipping...
2024-09-26 19:06:11,120 - INFO - Model for feature 'nbo_lp_P_percent_s_boltz' already exists, skipping...
2024-09-26 19:06:11,120 - INFO - Model for feature 'nbo_lp_P_occ_boltz' already exists, skipping...
2024-09-26 19:06:11,125 - INFO - Model for feature 'nbo_lp_P_e_boltz' already exists, skipping...
2024-09-26 19:06:11,127 - INFO - Model for feature 'nbo_bd_e_max_boltz' already exists, skipping...
2024-09-26 19:06:11,127 - INFO - Model for feature 'nbo_bd_e_avg_boltz' already exists, skipping...
2024-09-26 19:06:11,127 - INFO - Model for feature 'nbo_bds_e_min_boltz' already exists, skipping...
2024-09-26 19:06:11,127 - INFO - Model for feature 'nbo_bds_e_avg_boltz' already exists, skipping...
2024-09-26 19:06:11,134 - INFO - Model for feature 'nbo_bd_occ_min_boltz' already exists, skipping...
2024-09-26 19:06:11,137 - INFO - Model for feature 'nbo_bd_occ_avg_boltz' already exists, skipping...
2024-09-26 19:06:11,140 - INFO - Model for feature 'nbo_bds_occ_max_boltz' already exists, skipping...
2024-09-26 19:06:11,141 - INFO - Model for feature 'nbo_bds_occ_avg_boltz' already exists, skipping...
2024-09-26 19:06:11,141 - INFO - Model for feature 'E_solv_total_boltz' already exists, skipping...
2024-09-26 19:06:11,145 - INFO - Model for feature 'E_solv_elstat_boltz' already exists, skipping...
2024-09-26 19:06:11,147 - INFO - Model for feature 'E_oxidation_boltz' already exists, skipping...
2024-09-26 19:06:11,150 - INFO - Model for feature 'E_reduction_boltz' already exists, skipping...
2024-09-26 19:06:11,150 - INFO - Model for feature 'fukui_p_boltz' already exists, skipping...
2024-09-26 19:06:11,150 - INFO - Model for feature 'fukui_m_boltz' already exists, skipping...
2024-09-26 19:06:11,150 - INFO - Model for feature 'vbur_vtot_boltz' already exists, skipping...
2024-09-26 19:06:11,159 - INFO - Model for feature 'vbur_ratio_vbur_vtot_boltz' already exists, skipping...
2024-09-26 19:06:11,162 - INFO - Model for feature 'Pint_P_int_boltz' already exists, skipping...
2024-09-26 19:06:11,163 - INFO - Model for feature 'Pint_dP_boltz' already exists, skipping...
2024-09-26 19:06:11,165 - INFO - Model for feature 'Pint_P_min_boltz' already exists, skipping...
2024-09-26 19:06:11,167 - INFO - Model for feature 'Pint_P_max_boltz' already exists, skipping...
2024-09-26 19:06:11,169 - INFO - Model for feature 'volume_boltz' already exists, skipping...
2024-09-26 19:06:11,172 - INFO - Model for feature 'surface_area_boltz' already exists, skipping...
2024-09-26 19:06:11,173 - INFO - Model for feature 'sphericity_boltz' already exists, skipping...
2024-09-26 19:06:11,175 - INFO - Model for feature 'dipolemoment_boltz' already exists, skipping...
2024-09-26 19:06:11,175 - INFO - Model for feature 'dipolemoment_min' already exists, skipping...
2024-09-26 19:06:11,175 - INFO - Model for feature 'dipolemoment_max' already exists, skipping...
2024-09-26 19:06:11,175 - INFO - Model for feature 'dipolemoment_delta' already exists, skipping...
2024-09-26 19:06:11,175 - INFO - Model for feature 'dipolemoment_vburminconf' already exists, skipping...
2024-09-26 19:06:11,186 - INFO - Model for feature 'qpole_amp_boltz' already exists, skipping...
2024-09-26 19:06:11,188 - INFO - Model for feature 'qpole_amp_min' already exists, skipping...
2024-09-26 19:06:11,190 - INFO - Model for feature 'qpole_amp_max' already exists, skipping...
2024-09-26 19:06:11,192 - INFO - Model for feature 'qpole_amp_delta' already exists, skipping...
2024-09-26 19:06:11,194 - INFO - Model for feature 'qpole_amp_vburminconf' already exists, skipping...
2024-09-26 19:06:11,198 - INFO - Model for feature 'qpoletens_xx_boltz' already exists, skipping...
2024-09-26 19:06:11,201 - INFO - Model for feature 'qpoletens_xx_min' already exists, skipping...
2024-09-26 19:06:11,203 - INFO - Model for feature 'qpoletens_xx_max' already exists, skipping...
2024-09-26 19:06:11,205 - INFO - Model for feature 'qpoletens_xx_delta' already exists, skipping...
2024-09-26 19:06:11,207 - INFO - Model for feature 'qpoletens_xx_vburminconf' already exists, skipping...
2024-09-26 19:06:11,209 - INFO - Model for feature 'qpoletens_yy_boltz' already exists, skipping...
2024-09-26 19:06:11,210 - INFO - Model for feature 'qpoletens_yy_min' already exists, skipping...
2024-09-26 19:06:11,211 - INFO - Model for feature 'qpoletens_yy_max' already exists, skipping...
2024-09-26 19:06:11,213 - INFO - Model for feature 'qpoletens_yy_delta' already exists, skipping...
2024-09-26 19:06:11,214 - INFO - Model for feature 'qpoletens_yy_vburminconf' already exists, skipping...
2024-09-26 19:06:11,216 - INFO - Model for feature 'qpoletens_zz_boltz' already exists, skipping...
2024-09-26 19:06:11,218 - INFO - Model for feature 'qpoletens_zz_min' already exists, skipping...
2024-09-26 19:06:11,219 - INFO - Model for feature 'qpoletens_zz_max' already exists, skipping...
2024-09-26 19:06:11,221 - INFO - Model for feature 'qpoletens_zz_delta' already exists, skipping...
2024-09-26 19:06:11,223 - INFO - Model for feature 'qpoletens_zz_vburminconf' already exists, skipping...
2024-09-26 19:06:11,224 - INFO - Model for feature 'pyr_P_boltz' already exists, skipping...
2024-09-26 19:06:11,225 - INFO - Model for feature 'pyr_P_min' already exists, skipping...
2024-09-26 19:06:11,227 - INFO - Model for feature 'pyr_P_max' already exists, skipping...
2024-09-26 19:06:11,228 - INFO - Model for feature 'pyr_P_delta' already exists, skipping...
2024-09-26 19:06:11,230 - INFO - Model for feature 'pyr_P_vburminconf' already exists, skipping...
2024-09-26 19:06:11,231 - INFO - Model for feature 'pyr_alpha_boltz' already exists, skipping...
2024-09-26 19:06:11,233 - INFO - Model for feature 'pyr_alpha_min' already exists, skipping...
2024-09-26 19:06:11,234 - INFO - Model for feature 'pyr_alpha_max' already exists, skipping...
2024-09-26 19:06:11,235 - INFO - Model for feature 'pyr_alpha_delta' already exists, skipping...
2024-09-26 19:06:11,236 - INFO - Model for feature 'pyr_alpha_vburminconf' already exists, skipping...
2024-09-26 19:06:11,238 - INFO - Model for feature 'vbur_vbur_boltz' already exists, skipping...
2024-09-26 19:06:11,240 - INFO - Model for feature 'vbur_vbur_min' already exists, skipping...
2024-09-26 19:06:11,241 - INFO - Model for feature 'vbur_vbur_max' already exists, skipping...
2024-09-26 19:06:11,243 - INFO - Model for feature 'vbur_vbur_delta' already exists, skipping...
2024-09-26 19:06:11,244 - INFO - Model for feature 'vbur_vbur_vburminconf' already exists, skipping...
2024-09-26 19:06:11,246 - INFO - Model for feature 'vbur_qvbur_min_boltz' already exists, skipping...
2024-09-26 19:06:11,247 - INFO - Model for feature 'vbur_qvbur_min_min' already exists, skipping...
2024-09-26 19:06:11,249 - INFO - Model for feature 'vbur_qvbur_min_max' already exists, skipping...
2024-09-26 19:06:11,251 - INFO - Model for feature 'vbur_qvbur_min_delta' already exists, skipping...
2024-09-26 19:06:11,252 - INFO - Model for feature 'vbur_qvbur_min_vburminconf' already exists, skipping...
2024-09-26 19:06:11,253 - INFO - Model for feature 'vbur_qvbur_max_boltz' already exists, skipping...
2024-09-26 19:06:11,253 - INFO - Model for feature 'vbur_qvbur_max_min' already exists, skipping...
2024-09-26 19:06:11,258 - INFO - Model for feature 'vbur_qvbur_max_max' already exists, skipping...
2024-09-26 19:06:11,258 - INFO - Model for feature 'vbur_qvbur_max_delta' already exists, skipping...
2024-09-26 19:06:11,258 - INFO - Model for feature 'vbur_qvbur_max_vburminconf' already exists, skipping...
2024-09-26 19:06:11,258 - INFO - Model for feature 'vbur_qvtot_min_boltz' already exists, skipping...
2024-09-26 19:06:11,258 - INFO - Model for feature 'vbur_qvtot_min_min' already exists, skipping...
2024-09-26 19:06:11,258 - INFO - Model for feature 'vbur_qvtot_min_max' already exists, skipping...
2024-09-26 19:06:11,267 - INFO - Model for feature 'vbur_qvtot_min_delta' already exists, skipping...
2024-09-26 19:06:11,270 - INFO - Model for feature 'vbur_qvtot_min_vburminconf' already exists, skipping...
2024-09-26 19:06:11,271 - INFO - Model for feature 'vbur_qvtot_max_boltz' already exists, skipping...
2024-09-26 19:06:11,273 - INFO - Model for feature 'vbur_qvtot_max_min' already exists, skipping...
2024-09-26 19:06:11,274 - INFO - Model for feature 'vbur_qvtot_max_max' already exists, skipping...
2024-09-26 19:06:11,276 - INFO - Model for feature 'vbur_qvtot_max_delta' already exists, skipping...
2024-09-26 19:06:11,277 - INFO - Model for feature 'vbur_qvtot_max_vburminconf' already exists, skipping...
2024-09-26 19:06:11,279 - INFO - Model for feature 'vbur_max_delta_qvbur_boltz' already exists, skipping...
2024-09-26 19:06:11,280 - INFO - Model for feature 'vbur_max_delta_qvbur_min' already exists, skipping...
2024-09-26 19:06:11,281 - INFO - Model for feature 'vbur_max_delta_qvbur_max' already exists, skipping...
2024-09-26 19:06:11,283 - INFO - Model for feature 'vbur_max_delta_qvbur_delta' already exists, skipping...
2024-09-26 19:06:11,284 - INFO - Model for feature 'vbur_max_delta_qvbur_vburminconf' already exists, skipping...
2024-09-26 19:06:11,284 - INFO - Model for feature 'vbur_max_delta_qvtot_boltz' already exists, skipping...
2024-09-26 19:06:11,290 - INFO - Model for feature 'vbur_max_delta_qvtot_min' already exists, skipping...
2024-09-26 19:06:11,292 - INFO - Model for feature 'vbur_max_delta_qvtot_max' already exists, skipping...
2024-09-26 19:06:11,294 - INFO - Model for feature 'vbur_max_delta_qvtot_delta' already exists, skipping...
2024-09-26 19:06:11,295 - INFO - Model for feature 'vbur_max_delta_qvtot_vburminconf' already exists, skipping...
2024-09-26 19:06:11,296 - INFO - Model for feature 'vbur_ovbur_min_boltz' already exists, skipping...
2024-09-26 19:06:11,298 - INFO - Model for feature 'vbur_ovbur_min_min' already exists, skipping...
2024-09-26 19:06:11,299 - INFO - Model for feature 'vbur_ovbur_min_max' already exists, skipping...
2024-09-26 19:06:11,301 - INFO - Model for feature 'vbur_ovbur_min_delta' already exists, skipping...
2024-09-26 19:06:11,302 - INFO - Model for feature 'vbur_ovbur_min_vburminconf' already exists, skipping...
2024-09-26 19:06:11,303 - INFO - Model for feature 'vbur_ovbur_max_boltz' already exists, skipping...
2024-09-26 19:06:11,305 - INFO - Model for feature 'vbur_ovbur_max_min' already exists, skipping...
2024-09-26 19:06:11,306 - INFO - Model for feature 'vbur_ovbur_max_max' already exists, skipping...
2024-09-26 19:06:11,307 - INFO - Model for feature 'vbur_ovbur_max_delta' already exists, skipping...
2024-09-26 19:06:11,309 - INFO - Model for feature 'vbur_ovbur_max_vburminconf' already exists, skipping...
2024-09-26 19:06:11,310 - INFO - Model for feature 'vbur_ovtot_min_boltz' already exists, skipping...
2024-09-26 19:06:11,312 - INFO - Model for feature 'vbur_ovtot_min_min' already exists, skipping...
2024-09-26 19:06:11,313 - INFO - Model for feature 'vbur_ovtot_min_max' already exists, skipping...
2024-09-26 19:06:11,315 - INFO - Model for feature 'vbur_ovtot_min_delta' already exists, skipping...
2024-09-26 19:06:11,316 - INFO - Model for feature 'vbur_ovtot_min_vburminconf' already exists, skipping...
2024-09-26 19:06:11,318 - INFO - Model for feature 'vbur_ovtot_max_boltz' already exists, skipping...
2024-09-26 19:06:11,319 - INFO - Model for feature 'vbur_ovtot_max_min' already exists, skipping...
2024-09-26 19:06:11,321 - INFO - Model for feature 'vbur_ovtot_max_max' already exists, skipping...
2024-09-26 19:06:11,322 - INFO - Model for feature 'vbur_ovtot_max_delta' already exists, skipping...
2024-09-26 19:06:11,324 - INFO - Model for feature 'vbur_ovtot_max_vburminconf' already exists, skipping...
2024-09-26 19:06:11,325 - INFO - Model for feature 'vbur_near_vbur_boltz' already exists, skipping...
2024-09-26 19:06:11,327 - INFO - Model for feature 'vbur_near_vbur_min' already exists, skipping...
2024-09-26 19:06:11,328 - INFO - Model for feature 'vbur_near_vbur_max' already exists, skipping...
2024-09-26 19:06:11,329 - INFO - Model for feature 'vbur_near_vbur_delta' already exists, skipping...
2024-09-26 19:06:11,331 - INFO - Model for feature 'vbur_near_vbur_vburminconf' already exists, skipping...
2024-09-26 19:06:11,333 - INFO - Model for feature 'vbur_far_vbur_boltz' already exists, skipping...
2024-09-26 19:06:11,333 - INFO - Model for feature 'vbur_far_vbur_min' already exists, skipping...
2024-09-26 19:06:11,333 - INFO - Model for feature 'vbur_far_vbur_max' already exists, skipping...
2024-09-26 19:06:11,336 - INFO - Model for feature 'vbur_far_vbur_delta' already exists, skipping...
2024-09-26 19:06:11,337 - INFO - Model for feature 'vbur_far_vbur_vburminconf' already exists, skipping...
2024-09-26 19:06:11,339 - INFO - Model for feature 'vbur_near_vtot_boltz' already exists, skipping...
2024-09-26 19:06:11,341 - INFO - Model for feature 'vbur_near_vtot_min' already exists, skipping...
2024-09-26 19:06:11,342 - INFO - Model for feature 'vbur_near_vtot_max' already exists, skipping...
2024-09-26 19:06:11,344 - INFO - Model for feature 'vbur_near_vtot_delta' already exists, skipping...
2024-09-26 19:06:11,345 - INFO - Model for feature 'vbur_near_vtot_vburminconf' already exists, skipping...
2024-09-26 19:06:11,346 - INFO - Model for feature 'vbur_far_vtot_boltz' already exists, skipping...
2024-09-26 19:06:11,348 - INFO - Model for feature 'vbur_far_vtot_min' already exists, skipping...
2024-09-26 19:06:11,349 - INFO - Model for feature 'vbur_far_vtot_max' already exists, skipping...
2024-09-26 19:06:11,351 - INFO - Model for feature 'vbur_far_vtot_delta' already exists, skipping...
2024-09-26 19:06:11,353 - INFO - Model for feature 'vbur_far_vtot_vburminconf' already exists, skipping...
2024-09-26 19:06:11,354 - INFO - Model for feature 'sterimol_B1_boltz' already exists, skipping...
2024-09-26 19:06:11,355 - INFO - Model for feature 'sterimol_B1_min' already exists, skipping...
2024-09-26 19:06:11,357 - INFO - Model for feature 'sterimol_B1_max' already exists, skipping...
2024-09-26 19:06:11,358 - INFO - Model for feature 'sterimol_B1_delta' already exists, skipping...
2024-09-26 19:06:11,360 - INFO - Model for feature 'sterimol_B1_vburminconf' already exists, skipping...
2024-09-26 19:06:11,361 - INFO - Model for feature 'sterimol_B5_boltz' already exists, skipping...
2024-09-26 19:06:11,363 - INFO - Model for feature 'sterimol_B5_min' already exists, skipping...
2024-09-26 19:06:11,364 - INFO - Model for feature 'sterimol_B5_max' already exists, skipping...
2024-09-26 19:06:11,366 - INFO - Model for feature 'sterimol_B5_delta' already exists, skipping...
2024-09-26 19:06:11,368 - INFO - Model for feature 'sterimol_B5_vburminconf' already exists, skipping...
2024-09-26 19:06:11,369 - INFO - Model for feature 'sterimol_L_boltz' already exists, skipping...
2024-09-26 19:06:11,370 - INFO - Model for feature 'sterimol_L_min' already exists, skipping...
2024-09-26 19:06:11,371 - INFO - Model for feature 'sterimol_L_max' already exists, skipping...
2024-09-26 19:06:11,373 - INFO - Model for feature 'sterimol_L_delta' already exists, skipping...
2024-09-26 19:06:11,374 - INFO - Model for feature 'sterimol_L_vburminconf' already exists, skipping...
2024-09-26 19:06:11,376 - INFO - Model for feature 'sterimol_burB1_boltz' already exists, skipping...
2024-09-26 19:06:11,378 - INFO - Model for feature 'sterimol_burB1_min' already exists, skipping...
2024-09-26 19:06:11,380 - INFO - Model for feature 'sterimol_burB1_max' already exists, skipping...
2024-09-26 19:06:11,382 - INFO - Model for feature 'sterimol_burB1_delta' already exists, skipping...
2024-09-26 19:06:11,382 - INFO - Model for feature 'sterimol_burB1_vburminconf' already exists, skipping...
2024-09-26 19:06:11,382 - INFO - Model for feature 'sterimol_burB5_boltz' already exists, skipping...
2024-09-26 19:06:11,386 - INFO - Model for feature 'sterimol_burB5_min' already exists, skipping...
2024-09-26 19:06:11,387 - INFO - Model for feature 'sterimol_burB5_max' already exists, skipping...
2024-09-26 19:06:11,388 - INFO - Model for feature 'sterimol_burB5_delta' already exists, skipping...
2024-09-26 19:06:11,390 - INFO - Model for feature 'sterimol_burB5_vburminconf' already exists, skipping...
2024-09-26 19:06:11,391 - INFO - Model for feature 'sterimol_burL_boltz' already exists, skipping...
2024-09-26 19:06:11,393 - INFO - Model for feature 'sterimol_burL_min' already exists, skipping...
2024-09-26 19:06:11,395 - INFO - Model for feature 'sterimol_burL_max' already exists, skipping...
2024-09-26 19:06:11,583 - INFO - Shapes for feature 'sterimol_burL_delta': X_train: (924, 1024), y_train: (924,)
[I 2024-09-26 19:06:11,599] A new study created in memory with name: no-name-f64247d1-d21f-43f7-9a00-32e3419e7d69
C:\Users\UTKARSH GUPTA\AppData\Local\Temp\ipykernel_18756\4112935901.py:31: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  learning_rate = trial.suggest_loguniform('learning_rate', 1e-4, 1e-2)
D:\conda\Lib\site-packages\keras\src\layers\core\dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step

[I 2024-09-26 19:06:29,303] Trial 0 finished with value: 0.39816161618356966 and parameters: {'n_layers': 4, 'n_units': 244, 'dropout_rate': 0.11418895952590641, 'learning_rate': 0.0003673437183215118, 'batch_size': 89}. Best is trial 0 with value: 0.39816161618356966.
C:\Users\UTKARSH GUPTA\AppData\Local\Temp\ipykernel_18756\4112935901.py:31: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  learning_rate = trial.suggest_loguniform('learning_rate', 1e-4, 1e-2)
D:\conda\Lib\site-packages\keras\src\layers\core\dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step

[I 2024-09-26 19:06:35,654] Trial 1 finished with value: 0.4144556965334086 and parameters: {'n_layers': 1, 'n_units': 24, 'dropout_rate': 0.11884645695021734, 'learning_rate': 0.0005599465537515061, 'batch_size': 75}. Best is trial 0 with value: 0.39816161618356966.
C:\Users\UTKARSH GUPTA\AppData\Local\Temp\ipykernel_18756\4112935901.py:31: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  learning_rate = trial.suggest_loguniform('learning_rate', 1e-4, 1e-2)
D:\conda\Lib\site-packages\keras\src\layers\core\dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step

[I 2024-09-26 19:06:46,970] Trial 2 finished with value: 0.464340220477658 and parameters: {'n_layers': 4, 'n_units': 100, 'dropout_rate': 0.05003828329492355, 'learning_rate': 0.00046874592433501067, 'batch_size': 25}. Best is trial 0 with value: 0.39816161618356966.
C:\Users\UTKARSH GUPTA\AppData\Local\Temp\ipykernel_18756\4112935901.py:31: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  learning_rate = trial.suggest_loguniform('learning_rate', 1e-4, 1e-2)
D:\conda\Lib\site-packages\keras\src\layers\core\dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step

[I 2024-09-26 19:07:02,211] Trial 3 finished with value: 0.42113053827940244 and parameters: {'n_layers': 3, 'n_units': 17, 'dropout_rate': 0.01475838015201103, 'learning_rate': 0.00043911599695165845, 'batch_size': 37}. Best is trial 0 with value: 0.39816161618356966.
C:\Users\UTKARSH GUPTA\AppData\Local\Temp\ipykernel_18756\4112935901.py:31: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  learning_rate = trial.suggest_loguniform('learning_rate', 1e-4, 1e-2)
D:\conda\Lib\site-packages\keras\src\layers\core\dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step

[I 2024-09-26 19:07:20,172] Trial 4 finished with value: 0.4278659016323887 and parameters: {'n_layers': 4, 'n_units': 26, 'dropout_rate': 0.36407132305418843, 'learning_rate': 0.0003584965139705697, 'batch_size': 95}. Best is trial 0 with value: 0.39816161618356966.
C:\Users\UTKARSH GUPTA\AppData\Local\Temp\ipykernel_18756\4112935901.py:31: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  learning_rate = trial.suggest_loguniform('learning_rate', 1e-4, 1e-2)
D:\conda\Lib\site-packages\keras\src\layers\core\dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step

[I 2024-09-26 19:07:33,132] Trial 5 finished with value: 0.3015790680154089 and parameters: {'n_layers': 4, 'n_units': 240, 'dropout_rate': 0.4679331425916136, 'learning_rate': 0.004064811650879278, 'batch_size': 78}. Best is trial 5 with value: 0.3015790680154089.
C:\Users\UTKARSH GUPTA\AppData\Local\Temp\ipykernel_18756\4112935901.py:31: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  learning_rate = trial.suggest_loguniform('learning_rate', 1e-4, 1e-2)
D:\conda\Lib\site-packages\keras\src\layers\core\dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step

[I 2024-09-26 19:07:42,914] Trial 6 finished with value: 0.323360944559225 and parameters: {'n_layers': 3, 'n_units': 246, 'dropout_rate': 0.2972559603746376, 'learning_rate': 0.006783167915344709, 'batch_size': 93}. Best is trial 5 with value: 0.3015790680154089.
C:\Users\UTKARSH GUPTA\AppData\Local\Temp\ipykernel_18756\4112935901.py:31: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  learning_rate = trial.suggest_loguniform('learning_rate', 1e-4, 1e-2)
D:\conda\Lib\site-packages\keras\src\layers\core\dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step

[I 2024-09-26 19:07:53,715] Trial 7 finished with value: 0.5754178268736245 and parameters: {'n_layers': 5, 'n_units': 93, 'dropout_rate': 0.1141591242638676, 'learning_rate': 0.0014662801658708868, 'batch_size': 91}. Best is trial 5 with value: 0.3015790680154089.
C:\Users\UTKARSH GUPTA\AppData\Local\Temp\ipykernel_18756\4112935901.py:31: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  learning_rate = trial.suggest_loguniform('learning_rate', 1e-4, 1e-2)
D:\conda\Lib\site-packages\keras\src\layers\core\dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step

[I 2024-09-26 19:08:02,105] Trial 8 finished with value: 0.3308132326186413 and parameters: {'n_layers': 1, 'n_units': 59, 'dropout_rate': 0.4194849563135881, 'learning_rate': 0.001152498683192831, 'batch_size': 87}. Best is trial 5 with value: 0.3015790680154089.
C:\Users\UTKARSH GUPTA\AppData\Local\Temp\ipykernel_18756\4112935901.py:31: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  learning_rate = trial.suggest_loguniform('learning_rate', 1e-4, 1e-2)
D:\conda\Lib\site-packages\keras\src\layers\core\dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step

[I 2024-09-26 19:08:14,063] Trial 9 finished with value: 0.3211331006468769 and parameters: {'n_layers': 2, 'n_units': 136, 'dropout_rate': 0.05117551266669307, 'learning_rate': 0.0010952659746578653, 'batch_size': 89}. Best is trial 5 with value: 0.3015790680154089.
D:\conda\Lib\site-packages\keras\src\layers\core\dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 3ms/step

2024-09-26 19:08:28,763 - WARNING - You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.
2024-09-26 19:08:28,854 - INFO - Model for feature 'sterimol_burL_delta' saved successfully.
2024-09-26 19:08:29,006 - INFO - Shapes for feature 'sterimol_burL_vburminconf': X_train: (924, 1024), y_train: (924,)
[I 2024-09-26 19:08:29,006] A new study created in memory with name: no-name-d013b1f4-3f19-40ac-8287-fafa6db093f6
C:\Users\UTKARSH GUPTA\AppData\Local\Temp\ipykernel_18756\4112935901.py:31: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  learning_rate = trial.suggest_loguniform('learning_rate', 1e-4, 1e-2)
D:\conda\Lib\site-packages\keras\src\layers\core\dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step

[I 2024-09-26 19:08:37,739] Trial 0 finished with value: 0.6959570846418188 and parameters: {'n_layers': 2, 'n_units': 216, 'dropout_rate': 0.15341304108405163, 'learning_rate': 0.0007445731208785083, 'batch_size': 110}. Best is trial 0 with value: 0.6959570846418188.
C:\Users\UTKARSH GUPTA\AppData\Local\Temp\ipykernel_18756\4112935901.py:31: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  learning_rate = trial.suggest_loguniform('learning_rate', 1e-4, 1e-2)
D:\conda\Lib\site-packages\keras\src\layers\core\dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step

[I 2024-09-26 19:08:45,845] Trial 1 finished with value: 0.30775151700990827 and parameters: {'n_layers': 3, 'n_units': 83, 'dropout_rate': 0.017610163500801745, 'learning_rate': 0.006126108737403456, 'batch_size': 44}. Best is trial 1 with value: 0.30775151700990827.
C:\Users\UTKARSH GUPTA\AppData\Local\Temp\ipykernel_18756\4112935901.py:31: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  learning_rate = trial.suggest_loguniform('learning_rate', 1e-4, 1e-2)
D:\conda\Lib\site-packages\keras\src\layers\core\dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step

[I 2024-09-26 19:09:00,067] Trial 2 finished with value: 0.9349457788122932 and parameters: {'n_layers': 4, 'n_units': 111, 'dropout_rate': 0.4251379925749805, 'learning_rate': 0.000432378055723843, 'batch_size': 122}. Best is trial 1 with value: 0.30775151700990827.
C:\Users\UTKARSH GUPTA\AppData\Local\Temp\ipykernel_18756\4112935901.py:31: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  learning_rate = trial.suggest_loguniform('learning_rate', 1e-4, 1e-2)
D:\conda\Lib\site-packages\keras\src\layers\core\dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step

[I 2024-09-26 19:09:03,006] Trial 3 finished with value: 1.5147120034502557 and parameters: {'n_layers': 1, 'n_units': 39, 'dropout_rate': 0.1565615957376541, 'learning_rate': 0.007050178384448291, 'batch_size': 81}. Best is trial 1 with value: 0.30775151700990827.
C:\Users\UTKARSH GUPTA\AppData\Local\Temp\ipykernel_18756\4112935901.py:31: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  learning_rate = trial.suggest_loguniform('learning_rate', 1e-4, 1e-2)
D:\conda\Lib\site-packages\keras\src\layers\core\dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step

[I 2024-09-26 19:09:06,139] Trial 4 finished with value: 1.0346978310508677 and parameters: {'n_layers': 1, 'n_units': 166, 'dropout_rate': 0.2720969881564842, 'learning_rate': 0.004567256007761021, 'batch_size': 125}. Best is trial 1 with value: 0.30775151700990827.
C:\Users\UTKARSH GUPTA\AppData\Local\Temp\ipykernel_18756\4112935901.py:31: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  learning_rate = trial.suggest_loguniform('learning_rate', 1e-4, 1e-2)
D:\conda\Lib\site-packages\keras\src\layers\core\dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step

[I 2024-09-26 19:09:13,313] Trial 5 finished with value: 1.6094412266165306 and parameters: {'n_layers': 1, 'n_units': 17, 'dropout_rate': 0.2848017689326467, 'learning_rate': 0.0008462500891123217, 'batch_size': 114}. Best is trial 1 with value: 0.30775151700990827.
C:\Users\UTKARSH GUPTA\AppData\Local\Temp\ipykernel_18756\4112935901.py:31: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  learning_rate = trial.suggest_loguniform('learning_rate', 1e-4, 1e-2)
D:\conda\Lib\site-packages\keras\src\layers\core\dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step

[I 2024-09-26 19:09:34,916] Trial 6 finished with value: 0.743088257675365 and parameters: {'n_layers': 2, 'n_units': 178, 'dropout_rate': 0.2783238549762902, 'learning_rate': 0.0001559590363899658, 'batch_size': 45}. Best is trial 1 with value: 0.30775151700990827.
C:\Users\UTKARSH GUPTA\AppData\Local\Temp\ipykernel_18756\4112935901.py:31: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  learning_rate = trial.suggest_loguniform('learning_rate', 1e-4, 1e-2)
D:\conda\Lib\site-packages\keras\src\layers\core\dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step

[I 2024-09-26 19:09:53,716] Trial 7 finished with value: 0.887644554994556 and parameters: {'n_layers': 4, 'n_units': 221, 'dropout_rate': 0.24240544572219003, 'learning_rate': 0.00026828869576263413, 'batch_size': 105}. Best is trial 1 with value: 0.30775151700990827.
C:\Users\UTKARSH GUPTA\AppData\Local\Temp\ipykernel_18756\4112935901.py:31: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  learning_rate = trial.suggest_loguniform('learning_rate', 1e-4, 1e-2)
D:\conda\Lib\site-packages\keras\src\layers\core\dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step

[I 2024-09-26 19:10:05,589] Trial 8 finished with value: 0.32666958469861557 and parameters: {'n_layers': 5, 'n_units': 91, 'dropout_rate': 0.12307118890353214, 'learning_rate': 0.0032961546827881957, 'batch_size': 73}. Best is trial 1 with value: 0.30775151700990827.
C:\Users\UTKARSH GUPTA\AppData\Local\Temp\ipykernel_18756\4112935901.py:31: FutureWarning: suggest_loguniform has been deprecated in v3.0.0. This feature will be removed in v6.0.0. See https://github.com/optuna/optuna/releases/tag/v3.0.0. Use suggest_float(..., log=True) instead.
  learning_rate = trial.suggest_loguniform('learning_rate', 1e-4, 1e-2)
D:\conda\Lib\site-packages\keras\src\layers\core\dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step

[I 2024-09-26 19:10:11,573] Trial 9 finished with value: 6.362979532033261 and parameters: {'n_layers': 2, 'n_units': 44, 'dropout_rate': 0.04253330800344379, 'learning_rate': 0.0001170117784801829, 'batch_size': 30}. Best is trial 1 with value: 0.30775151700990827.
D:\conda\Lib\site-packages\keras\src\layers\core\dense.py:87: UserWarning: Do not pass an `input_shape`/`input_dim` argument to a layer. When using Sequential models, prefer using an `Input(shape)` object as the first layer in the model instead.
  super().__init__(activity_regularizer=activity_regularizer, **kwargs)

10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 2ms/step

2024-09-26 19:10:19,533 - WARNING - You are saving your model as an HDF5 file via `model.save()` or `keras.saving.save_model(model)`. This file format is considered legacy. We recommend using instead the native Keras format, e.g. `model.save('my_model.keras')` or `keras.saving.save_model(model, 'my_model.keras')`.
2024-09-26 19:10:19,577 - INFO - Model for feature 'sterimol_burL_vburminconf' saved successfully.
2024-09-26 19:10:19,588 - INFO - Best model performance metrics saved to 'model_performance_dl.csv'.
2024-09-26 19:10:19,588 - INFO - Best models saved in the 'models_dl_bayes_val_cv' directory.

In [31]:
from keras.models import load_model

In [57]:
logging.basicConfig(level=logging.INFO, format='%(asctime)s - %(levelname)s - %(message)s')

X = input
Y = abb.copy() 

# Split the data into train, validation, and test sets
X_train, X_temp, y_train, y_temp = train_test_split(X, Y, test_size=0.4, random_state=42)
X_val, X_test, y_val, y_test = train_test_split(X_temp, y_temp, test_size=0.5, random_state=42)

# Define the model directory and result storage
model_dir = 'models_dl_bayes_val_cv'
results_list = []

 

# Iterate through each model file in the model directory
for model_file in os.listdir(model_dir):
    if model_file.endswith('.h5'):
        print(model_file)
        # Extract the feature name from the filename
        feature = model_file[6:-3]  # Remove 'model_' from the start and '.h5' from the end
        model_path = os.path.join(model_dir, model_file)
        # Load the model
        model = load_model(model_path)

        # Predict using the model on the test set
        y_pred = model.predict(X_test)
        
        # Log shapes and types
        logging.info("Shapes: y_test: %s, y_pred: %s", y_test.shape, y_pred.shape)
        logging.info("Types: y_test: %s, y_pred: %s", type(y_test), type(y_pred))
        
        # Calculate MAE and R²
        test_mae = mean_absolute_error(y_test[feature], y_pred)
        r2 = r2_score(y_test[feature], y_pred)

        
        # Store the results
        results_list.append({
            'Feature': feature,
            'Test MAE': test_mae,
            'R²': r2
        })
        
        logging.info(f"Model for feature '{feature}' evaluated. Test MAE: {test_mae}, R²: {r2}")

# Save all results to a CSV file
results_df = pd.DataFrame(results_list)
results_df.to_csv('model_evaluation_metrics.csv', index=False)
logging.info("Model evaluation metrics saved to 'model_evaluation_metrics.csv'.")

2024-09-26 19:22:55,201 - WARNING - Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.

model_dipolemoment_boltz.h5
dipolemoment_boltz
dipolemoment_boltz
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step

2024-09-26 19:22:55,570 - INFO - Shapes: y_test: (308, 190), y_pred: (308, 1)
2024-09-26 19:22:55,573 - INFO - Types: y_test: <class 'pandas.core.frame.DataFrame'>, y_pred: <class 'numpy.ndarray'>
2024-09-26 19:22:55,574 - INFO - Model for feature 'dipolemoment_boltz' evaluated. Test MAE: 0.5146547691934446, R²: 0.5961482435182335

model_dipolemoment_delta.h5
dipolemoment_delta
dipolemoment_delta

2024-09-26 19:22:55,822 - WARNING - Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.

10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 26ms/step

2024-09-26 19:22:56,424 - INFO - Shapes: y_test: (308, 190), y_pred: (308, 1)
2024-09-26 19:22:56,424 - INFO - Types: y_test: <class 'pandas.core.frame.DataFrame'>, y_pred: <class 'numpy.ndarray'>
2024-09-26 19:22:56,424 - INFO - Model for feature 'dipolemoment_delta' evaluated. Test MAE: 0.6214552597198653, R²: 0.3674561826299042
2024-09-26 19:22:56,550 - WARNING - Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.

model_dipolemoment_max.h5
dipolemoment_max
dipolemoment_max
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step

2024-09-26 19:22:56,939 - INFO - Shapes: y_test: (308, 190), y_pred: (308, 1)
2024-09-26 19:22:56,939 - INFO - Types: y_test: <class 'pandas.core.frame.DataFrame'>, y_pred: <class 'numpy.ndarray'>
2024-09-26 19:22:56,939 - INFO - Model for feature 'dipolemoment_max' evaluated. Test MAE: 0.9956376013353282, R²: 0.11259226191319949

model_dipolemoment_min.h5
dipolemoment_min
dipolemoment_min

2024-09-26 19:22:57,149 - WARNING - Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.

10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step

2024-09-26 19:22:57,665 - INFO - Shapes: y_test: (308, 190), y_pred: (308, 1)
2024-09-26 19:22:57,665 - INFO - Types: y_test: <class 'pandas.core.frame.DataFrame'>, y_pred: <class 'numpy.ndarray'>
2024-09-26 19:22:57,670 - INFO - Model for feature 'dipolemoment_min' evaluated. Test MAE: 0.5136367810270035, R²: 0.43634829568876177

model_dipolemoment_vburminconf.h5
dipolemoment_vburminconf
dipolemoment_vburminconf

2024-09-26 19:22:57,899 - WARNING - Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.

10/10 ━━━━━━━━━━━━━━━━━━━━ 1s 22ms/step

2024-09-26 19:22:59,006 - INFO - Shapes: y_test: (308, 190), y_pred: (308, 1)
2024-09-26 19:22:59,007 - INFO - Types: y_test: <class 'pandas.core.frame.DataFrame'>, y_pred: <class 'numpy.ndarray'>
2024-09-26 19:22:59,008 - INFO - Model for feature 'dipolemoment_vburminconf' evaluated. Test MAE: 0.6703761126320569, R²: 0.44534181543304185
2024-09-26 19:22:59,162 - WARNING - Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.

model_efgtens_xx_P_boltz.h5
efgtens_xx_P_boltz
efgtens_xx_P_boltz
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step

2024-09-26 19:22:59,542 - INFO - Shapes: y_test: (308, 190), y_pred: (308, 1)
2024-09-26 19:22:59,542 - INFO - Types: y_test: <class 'pandas.core.frame.DataFrame'>, y_pred: <class 'numpy.ndarray'>
2024-09-26 19:22:59,542 - INFO - Model for feature 'efgtens_xx_P_boltz' evaluated. Test MAE: 0.0906682387748076, R²: 0.5168320637186312

model_efgtens_yy_P_boltz.h5
efgtens_yy_P_boltz
efgtens_yy_P_boltz

2024-09-26 19:22:59,746 - WARNING - Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.

10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step

2024-09-26 19:23:00,226 - INFO - Shapes: y_test: (308, 190), y_pred: (308, 1)
2024-09-26 19:23:00,226 - INFO - Types: y_test: <class 'pandas.core.frame.DataFrame'>, y_pred: <class 'numpy.ndarray'>
2024-09-26 19:23:00,226 - INFO - Model for feature 'efgtens_yy_P_boltz' evaluated. Test MAE: 0.07755837820276067, R²: 0.32170497683492394

model_efgtens_zz_P_boltz.h5
efgtens_zz_P_boltz
efgtens_zz_P_boltz

2024-09-26 19:23:00,338 - WARNING - Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.

10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step

2024-09-26 19:23:00,692 - INFO - Shapes: y_test: (308, 190), y_pred: (308, 1)
2024-09-26 19:23:00,693 - INFO - Types: y_test: <class 'pandas.core.frame.DataFrame'>, y_pred: <class 'numpy.ndarray'>
2024-09-26 19:23:00,695 - INFO - Model for feature 'efgtens_zz_P_boltz' evaluated. Test MAE: 0.11282635930995019, R²: 0.09859781145183

model_efg_amp_P_boltz.h5
efg_amp_P_boltz
efg_amp_P_boltz

2024-09-26 19:23:00,789 - WARNING - Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.

10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step

2024-09-26 19:23:01,140 - INFO - Shapes: y_test: (308, 190), y_pred: (308, 1)
2024-09-26 19:23:01,140 - INFO - Types: y_test: <class 'pandas.core.frame.DataFrame'>, y_pred: <class 'numpy.ndarray'>
2024-09-26 19:23:01,155 - INFO - Model for feature 'efg_amp_P_boltz' evaluated. Test MAE: 0.08814127938063426, R²: 0.5526209564972194

model_E_oxidation_boltz.h5
E_oxidation_boltz
E_oxidation_boltz

2024-09-26 19:23:01,242 - WARNING - Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.

10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step

2024-09-26 19:23:01,504 - INFO - Shapes: y_test: (308, 190), y_pred: (308, 1)
2024-09-26 19:23:01,504 - INFO - Types: y_test: <class 'pandas.core.frame.DataFrame'>, y_pred: <class 'numpy.ndarray'>
2024-09-26 19:23:01,504 - INFO - Model for feature 'E_oxidation_boltz' evaluated. Test MAE: 0.012974421541472667, R²: 0.5577575001309873

model_E_reduction_boltz.h5
E_reduction_boltz
E_reduction_boltz

2024-09-26 19:23:01,758 - WARNING - Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.

10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step

2024-09-26 19:23:02,256 - INFO - Shapes: y_test: (308, 190), y_pred: (308, 1)
2024-09-26 19:23:02,256 - INFO - Types: y_test: <class 'pandas.core.frame.DataFrame'>, y_pred: <class 'numpy.ndarray'>
2024-09-26 19:23:02,256 - INFO - Model for feature 'E_reduction_boltz' evaluated. Test MAE: 0.01813025387088251, R²: 0.37626488855971685
2024-09-26 19:23:02,396 - WARNING - Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.

model_E_solv_cds_boltz.h5
E_solv_cds_boltz
E_solv_cds_boltz
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step

2024-09-26 19:23:02,830 - INFO - Shapes: y_test: (308, 190), y_pred: (308, 1)
2024-09-26 19:23:02,831 - INFO - Types: y_test: <class 'pandas.core.frame.DataFrame'>, y_pred: <class 'numpy.ndarray'>
2024-09-26 19:23:02,832 - INFO - Model for feature 'E_solv_cds_boltz' evaluated. Test MAE: 1.2283257573637185, R²: 0.7529464929668541
2024-09-26 19:23:02,919 - WARNING - Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.

model_E_solv_elstat_boltz.h5
E_solv_elstat_boltz
E_solv_elstat_boltz
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step

2024-09-26 19:23:03,245 - INFO - Shapes: y_test: (308, 190), y_pred: (308, 1)
2024-09-26 19:23:03,245 - INFO - Types: y_test: <class 'pandas.core.frame.DataFrame'>, y_pred: <class 'numpy.ndarray'>
2024-09-26 19:23:03,253 - INFO - Model for feature 'E_solv_elstat_boltz' evaluated. Test MAE: 1.184541518852085, R²: 0.7203267946817219

model_E_solv_total_boltz.h5
E_solv_total_boltz
E_solv_total_boltz

2024-09-26 19:23:03,369 - WARNING - Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.

10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step

2024-09-26 19:23:03,726 - INFO - Shapes: y_test: (308, 190), y_pred: (308, 1)
2024-09-26 19:23:03,726 - INFO - Types: y_test: <class 'pandas.core.frame.DataFrame'>, y_pred: <class 'numpy.ndarray'>
2024-09-26 19:23:03,726 - INFO - Model for feature 'E_solv_total_boltz' evaluated. Test MAE: 1.9404040509982567, R²: 0.7444109691447514
2024-09-26 19:23:03,787 - WARNING - Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.

model_fmo_eta_boltz.h5
fmo_eta_boltz
fmo_eta_boltz
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step

2024-09-26 19:23:04,040 - INFO - Shapes: y_test: (308, 190), y_pred: (308, 1)
2024-09-26 19:23:04,040 - INFO - Types: y_test: <class 'pandas.core.frame.DataFrame'>, y_pred: <class 'numpy.ndarray'>
2024-09-26 19:23:04,040 - INFO - Model for feature 'fmo_eta_boltz' evaluated. Test MAE: 0.0139226793141264, R²: 0.6739671228597222

model_fmo_e_homo_boltz.h5
fmo_e_homo_boltz
fmo_e_homo_boltz

2024-09-26 19:23:04,221 - WARNING - Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.

10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step

2024-09-26 19:23:04,738 - INFO - Shapes: y_test: (308, 190), y_pred: (308, 1)
2024-09-26 19:23:04,738 - INFO - Types: y_test: <class 'pandas.core.frame.DataFrame'>, y_pred: <class 'numpy.ndarray'>
2024-09-26 19:23:04,742 - INFO - Model for feature 'fmo_e_homo_boltz' evaluated. Test MAE: 0.0160691978479806, R²: -0.09988452023836314
2024-09-26 19:23:04,794 - WARNING - Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.

model_fmo_e_lumo_boltz.h5
fmo_e_lumo_boltz
fmo_e_lumo_boltz
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step

2024-09-26 19:23:05,103 - INFO - Shapes: y_test: (308, 190), y_pred: (308, 1)
2024-09-26 19:23:05,105 - INFO - Types: y_test: <class 'pandas.core.frame.DataFrame'>, y_pred: <class 'numpy.ndarray'>
2024-09-26 19:23:05,106 - INFO - Model for feature 'fmo_e_lumo_boltz' evaluated. Test MAE: 0.011741393262218767, R²: 0.7218824252999116

model_fmo_mu_boltz.h5
fmo_mu_boltz
fmo_mu_boltz

2024-09-26 19:23:05,335 - WARNING - Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.

10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step

2024-09-26 19:23:05,813 - INFO - Shapes: y_test: (308, 190), y_pred: (308, 1)
2024-09-26 19:23:05,820 - INFO - Types: y_test: <class 'pandas.core.frame.DataFrame'>, y_pred: <class 'numpy.ndarray'>
2024-09-26 19:23:05,821 - INFO - Model for feature 'fmo_mu_boltz' evaluated. Test MAE: 0.014608709338548846, R²: -0.021246947508508418
2024-09-26 19:23:05,899 - WARNING - Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.

model_fmo_omega_boltz.h5
fmo_omega_boltz
fmo_omega_boltz
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step

2024-09-26 19:23:06,116 - INFO - Shapes: y_test: (308, 190), y_pred: (308, 1)
2024-09-26 19:23:06,116 - INFO - Types: y_test: <class 'pandas.core.frame.DataFrame'>, y_pred: <class 'numpy.ndarray'>
2024-09-26 19:23:06,121 - INFO - Model for feature 'fmo_omega_boltz' evaluated. Test MAE: 0.008307598563674575, R²: 0.48199176643447905

model_fukui_m_boltz.h5
fukui_m_boltz
fukui_m_boltz

2024-09-26 19:23:06,415 - WARNING - Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.

10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step

2024-09-26 19:23:06,854 - INFO - Shapes: y_test: (308, 190), y_pred: (308, 1)
2024-09-26 19:23:06,854 - INFO - Types: y_test: <class 'pandas.core.frame.DataFrame'>, y_pred: <class 'numpy.ndarray'>
2024-09-26 19:23:06,854 - INFO - Model for feature 'fukui_m_boltz' evaluated. Test MAE: 0.0671751592071314, R²: 0.7402220000629174

model_fukui_p_boltz.h5
fukui_p_boltz
fukui_p_boltz

2024-09-26 19:23:07,013 - WARNING - Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.

10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step

2024-09-26 19:23:07,405 - INFO - Shapes: y_test: (308, 190), y_pred: (308, 1)
2024-09-26 19:23:07,405 - INFO - Types: y_test: <class 'pandas.core.frame.DataFrame'>, y_pred: <class 'numpy.ndarray'>
2024-09-26 19:23:07,405 - INFO - Model for feature 'fukui_p_boltz' evaluated. Test MAE: 0.06955581145063934, R²: -0.10514058581516661

model_nbo_bds_e_avg_boltz.h5
nbo_bds_e_avg_boltz
nbo_bds_e_avg_boltz

2024-09-26 19:23:07,537 - WARNING - Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.

10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step

2024-09-26 19:23:07,821 - INFO - Shapes: y_test: (308, 190), y_pred: (308, 1)
2024-09-26 19:23:07,822 - INFO - Types: y_test: <class 'pandas.core.frame.DataFrame'>, y_pred: <class 'numpy.ndarray'>
2024-09-26 19:23:07,824 - INFO - Model for feature 'nbo_bds_e_avg_boltz' evaluated. Test MAE: 0.018362054658457024, R²: 0.04260760972250066

model_nbo_bds_e_min_boltz.h5
nbo_bds_e_min_boltz
nbo_bds_e_min_boltz

2024-09-26 19:23:07,954 - WARNING - Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.

10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step

2024-09-26 19:23:08,254 - INFO - Shapes: y_test: (308, 190), y_pred: (308, 1)
2024-09-26 19:23:08,254 - INFO - Types: y_test: <class 'pandas.core.frame.DataFrame'>, y_pred: <class 'numpy.ndarray'>
2024-09-26 19:23:08,254 - INFO - Model for feature 'nbo_bds_e_min_boltz' evaluated. Test MAE: 0.02649967200869299, R²: -0.4171062115808839
2024-09-26 19:23:08,319 - WARNING - Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.

model_nbo_bds_occ_avg_boltz.h5
nbo_bds_occ_avg_boltz
nbo_bds_occ_avg_boltz
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step

2024-09-26 19:23:08,628 - INFO - Shapes: y_test: (308, 190), y_pred: (308, 1)
2024-09-26 19:23:08,628 - INFO - Types: y_test: <class 'pandas.core.frame.DataFrame'>, y_pred: <class 'numpy.ndarray'>
2024-09-26 19:23:08,637 - INFO - Model for feature 'nbo_bds_occ_avg_boltz' evaluated. Test MAE: 0.01539098405183689, R²: 0.09867033607614906

model_nbo_bds_occ_max_boltz.h5
nbo_bds_occ_max_boltz
nbo_bds_occ_max_boltz

2024-09-26 19:23:08,738 - WARNING - Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.

10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step

2024-09-26 19:23:09,043 - INFO - Shapes: y_test: (308, 190), y_pred: (308, 1)
2024-09-26 19:23:09,044 - INFO - Types: y_test: <class 'pandas.core.frame.DataFrame'>, y_pred: <class 'numpy.ndarray'>
2024-09-26 19:23:09,046 - INFO - Model for feature 'nbo_bds_occ_max_boltz' evaluated. Test MAE: 0.018102506542483576, R²: 0.1296202731054077

model_nbo_bd_e_avg_boltz.h5
nbo_bd_e_avg_boltz
nbo_bd_e_avg_boltz

2024-09-26 19:23:09,186 - WARNING - Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.

10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step

2024-09-26 19:23:09,549 - INFO - Shapes: y_test: (308, 190), y_pred: (308, 1)
2024-09-26 19:23:09,549 - INFO - Types: y_test: <class 'pandas.core.frame.DataFrame'>, y_pred: <class 'numpy.ndarray'>
2024-09-26 19:23:09,553 - INFO - Model for feature 'nbo_bd_e_avg_boltz' evaluated. Test MAE: 0.06214440692160614, R²: -0.2532497746106188

model_nbo_bd_e_max_boltz.h5
nbo_bd_e_max_boltz
nbo_bd_e_max_boltz

2024-09-26 19:23:09,637 - WARNING - Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.

10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step

2024-09-26 19:23:09,903 - INFO - Shapes: y_test: (308, 190), y_pred: (308, 1)
2024-09-26 19:23:09,903 - INFO - Types: y_test: <class 'pandas.core.frame.DataFrame'>, y_pred: <class 'numpy.ndarray'>
2024-09-26 19:23:09,903 - INFO - Model for feature 'nbo_bd_e_max_boltz' evaluated. Test MAE: 0.029414526377310766, R²: 0.668150424059265

model_nbo_bd_occ_avg_boltz.h5
nbo_bd_occ_avg_boltz
nbo_bd_occ_avg_boltz

2024-09-26 19:23:10,086 - WARNING - Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.

10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step

2024-09-26 19:23:10,386 - INFO - Shapes: y_test: (308, 190), y_pred: (308, 1)
2024-09-26 19:23:10,386 - INFO - Types: y_test: <class 'pandas.core.frame.DataFrame'>, y_pred: <class 'numpy.ndarray'>
2024-09-26 19:23:10,386 - INFO - Model for feature 'nbo_bd_occ_avg_boltz' evaluated. Test MAE: 0.1370126314861882, R²: -393.73146048077456

model_nbo_bd_occ_min_boltz.h5
nbo_bd_occ_min_boltz
nbo_bd_occ_min_boltz

2024-09-26 19:23:10,537 - WARNING - Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.

10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step

2024-09-26 19:23:11,028 - INFO - Shapes: y_test: (308, 190), y_pred: (308, 1)
2024-09-26 19:23:11,030 - INFO - Types: y_test: <class 'pandas.core.frame.DataFrame'>, y_pred: <class 'numpy.ndarray'>
2024-09-26 19:23:11,032 - INFO - Model for feature 'nbo_bd_occ_min_boltz' evaluated. Test MAE: 0.03486511349534904, R²: -13.071751478625972
2024-09-26 19:23:11,100 - WARNING - Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.

model_nbo_lp_P_e_boltz.h5
nbo_lp_P_e_boltz
nbo_lp_P_e_boltz
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step

2024-09-26 19:23:11,354 - INFO - Shapes: y_test: (308, 190), y_pred: (308, 1)
2024-09-26 19:23:11,354 - INFO - Types: y_test: <class 'pandas.core.frame.DataFrame'>, y_pred: <class 'numpy.ndarray'>
2024-09-26 19:23:11,354 - INFO - Model for feature 'nbo_lp_P_e_boltz' evaluated. Test MAE: 0.023609035053425625, R²: 0.22795340946047105
2024-09-26 19:23:11,430 - WARNING - Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.

model_nbo_lp_P_occ_boltz.h5
nbo_lp_P_occ_boltz
nbo_lp_P_occ_boltz
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step

2024-09-26 19:23:11,671 - INFO - Shapes: y_test: (308, 190), y_pred: (308, 1)
2024-09-26 19:23:11,671 - INFO - Types: y_test: <class 'pandas.core.frame.DataFrame'>, y_pred: <class 'numpy.ndarray'>
2024-09-26 19:23:11,671 - INFO - Model for feature 'nbo_lp_P_occ_boltz' evaluated. Test MAE: 0.038245841657917966, R²: -1.6822003983711107

model_nbo_lp_P_percent_s_boltz.h5
nbo_lp_P_percent_s_boltz
nbo_lp_P_percent_s_boltz

2024-09-26 19:23:11,865 - WARNING - Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.

10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step

2024-09-26 19:23:12,287 - INFO - Shapes: y_test: (308, 190), y_pred: (308, 1)
2024-09-26 19:23:12,287 - INFO - Types: y_test: <class 'pandas.core.frame.DataFrame'>, y_pred: <class 'numpy.ndarray'>
2024-09-26 19:23:12,287 - INFO - Model for feature 'nbo_lp_P_percent_s_boltz' evaluated. Test MAE: 1.8889872372407985, R²: 0.7849606805808141

model_nbo_P_boltz.h5
nbo_P_boltz
nbo_P_boltz

2024-09-26 19:23:12,503 - WARNING - Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.

10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step

2024-09-26 19:23:13,034 - INFO - Shapes: y_test: (308, 190), y_pred: (308, 1)
2024-09-26 19:23:13,036 - INFO - Types: y_test: <class 'pandas.core.frame.DataFrame'>, y_pred: <class 'numpy.ndarray'>
2024-09-26 19:23:13,038 - INFO - Model for feature 'nbo_P_boltz' evaluated. Test MAE: 0.10507653893137546, R²: 0.6568449402258663
2024-09-26 19:23:13,147 - WARNING - Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.

model_nbo_P_ra_boltz.h5
nbo_P_ra_boltz
nbo_P_ra_boltz
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step

2024-09-26 19:23:13,471 - INFO - Shapes: y_test: (308, 190), y_pred: (308, 1)
2024-09-26 19:23:13,471 - INFO - Types: y_test: <class 'pandas.core.frame.DataFrame'>, y_pred: <class 'numpy.ndarray'>
2024-09-26 19:23:13,471 - INFO - Model for feature 'nbo_P_ra_boltz' evaluated. Test MAE: 0.11116839605289076, R²: 0.6532058087864769

model_nbo_P_rc_boltz.h5
nbo_P_rc_boltz
nbo_P_rc_boltz

2024-09-26 19:23:13,685 - WARNING - Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.

10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step

2024-09-26 19:23:14,121 - INFO - Shapes: y_test: (308, 190), y_pred: (308, 1)
2024-09-26 19:23:14,121 - INFO - Types: y_test: <class 'pandas.core.frame.DataFrame'>, y_pred: <class 'numpy.ndarray'>
2024-09-26 19:23:14,137 - INFO - Model for feature 'nbo_P_rc_boltz' evaluated. Test MAE: 0.12129415611135508, R²: 0.5774786669996965
2024-09-26 19:23:14,255 - WARNING - Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.

model_nmrtens_sxx_P_boltz.h5
nmrtens_sxx_P_boltz
nmrtens_sxx_P_boltz
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step

2024-09-26 19:23:14,594 - INFO - Shapes: y_test: (308, 190), y_pred: (308, 1)
2024-09-26 19:23:14,595 - INFO - Types: y_test: <class 'pandas.core.frame.DataFrame'>, y_pred: <class 'numpy.ndarray'>
2024-09-26 19:23:14,598 - INFO - Model for feature 'nmrtens_sxx_P_boltz' evaluated. Test MAE: 28.6564197898369, R²: 0.8325552298779516

model_nmrtens_syy_P_boltz.h5
nmrtens_syy_P_boltz
nmrtens_syy_P_boltz

2024-09-26 19:23:14,763 - WARNING - Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.

10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step

2024-09-26 19:23:15,222 - INFO - Shapes: y_test: (308, 190), y_pred: (308, 1)
2024-09-26 19:23:15,222 - INFO - Types: y_test: <class 'pandas.core.frame.DataFrame'>, y_pred: <class 'numpy.ndarray'>
2024-09-26 19:23:15,222 - INFO - Model for feature 'nmrtens_syy_P_boltz' evaluated. Test MAE: 24.501890293580644, R²: 0.8083140914951796
2024-09-26 19:23:15,398 - WARNING - Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.

model_nmrtens_szz_P_boltz.h5
nmrtens_szz_P_boltz
nmrtens_szz_P_boltz
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step

2024-09-26 19:23:15,837 - INFO - Shapes: y_test: (308, 190), y_pred: (308, 1)
2024-09-26 19:23:15,837 - INFO - Types: y_test: <class 'pandas.core.frame.DataFrame'>, y_pred: <class 'numpy.ndarray'>
2024-09-26 19:23:15,837 - INFO - Model for feature 'nmrtens_szz_P_boltz' evaluated. Test MAE: 37.7483378652813, R²: 0.16738139065058055
2024-09-26 19:23:15,994 - WARNING - Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.

model_nmr_P_boltz.h5
nmr_P_boltz
nmr_P_boltz
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step

2024-09-26 19:23:16,459 - INFO - Shapes: y_test: (308, 190), y_pred: (308, 1)
2024-09-26 19:23:16,459 - INFO - Types: y_test: <class 'pandas.core.frame.DataFrame'>, y_pred: <class 'numpy.ndarray'>
2024-09-26 19:23:16,459 - INFO - Model for feature 'nmr_P_boltz' evaluated. Test MAE: 21.496849786714122, R²: 0.7993747543236989

model_nuesp_P_boltz.h5
nuesp_P_boltz
nuesp_P_boltz

2024-09-26 19:23:16,520 - WARNING - Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.

10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step

2024-09-26 19:23:16,752 - INFO - Shapes: y_test: (308, 190), y_pred: (308, 1)
2024-09-26 19:23:16,768 - INFO - Types: y_test: <class 'pandas.core.frame.DataFrame'>, y_pred: <class 'numpy.ndarray'>
2024-09-26 19:23:16,770 - INFO - Model for feature 'nuesp_P_boltz' evaluated. Test MAE: 0.27798303623887083, R²: -109.51598707947556

model_Pint_dP_boltz.h5
Pint_dP_boltz
Pint_dP_boltz

2024-09-26 19:23:16,902 - WARNING - Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.

10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step

2024-09-26 19:23:17,316 - INFO - Shapes: y_test: (308, 190), y_pred: (308, 1)
2024-09-26 19:23:17,319 - INFO - Types: y_test: <class 'pandas.core.frame.DataFrame'>, y_pred: <class 'numpy.ndarray'>
2024-09-26 19:23:17,320 - INFO - Model for feature 'Pint_dP_boltz' evaluated. Test MAE: 0.29327411559938427, R²: 0.6806537469129587

model_Pint_P_int_boltz.h5
Pint_P_int_boltz
Pint_P_int_boltz

2024-09-26 19:23:17,395 - WARNING - Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.

10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step

2024-09-26 19:23:17,688 - INFO - Shapes: y_test: (308, 190), y_pred: (308, 1)
2024-09-26 19:23:17,688 - INFO - Types: y_test: <class 'pandas.core.frame.DataFrame'>, y_pred: <class 'numpy.ndarray'>
2024-09-26 19:23:17,688 - INFO - Model for feature 'Pint_P_int_boltz' evaluated. Test MAE: 5.225347126485724, R²: -15.473000837869911

model_Pint_P_max_boltz.h5
Pint_P_max_boltz
Pint_P_max_boltz

2024-09-26 19:23:17,937 - WARNING - Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.

10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 27ms/step

2024-09-26 19:23:18,492 - INFO - Shapes: y_test: (308, 190), y_pred: (308, 1)
2024-09-26 19:23:18,492 - INFO - Types: y_test: <class 'pandas.core.frame.DataFrame'>, y_pred: <class 'numpy.ndarray'>
2024-09-26 19:23:18,502 - INFO - Model for feature 'Pint_P_max_boltz' evaluated. Test MAE: 1.8132969527904166, R²: 0.6523053953598766

model_Pint_P_min_boltz.h5
Pint_P_min_boltz
Pint_P_min_boltz

2024-09-26 19:23:18,733 - WARNING - Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.

10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step

2024-09-26 19:23:19,220 - INFO - Shapes: y_test: (308, 190), y_pred: (308, 1)
2024-09-26 19:23:19,220 - INFO - Types: y_test: <class 'pandas.core.frame.DataFrame'>, y_pred: <class 'numpy.ndarray'>
2024-09-26 19:23:19,220 - INFO - Model for feature 'Pint_P_min_boltz' evaluated. Test MAE: 0.4615902093757054, R²: 0.7272930691469146
2024-09-26 19:23:19,369 - WARNING - Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.

model_pyr_alpha_boltz.h5
pyr_alpha_boltz
pyr_alpha_boltz
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step

2024-09-26 19:23:19,683 - INFO - Shapes: y_test: (308, 190), y_pred: (308, 1)
2024-09-26 19:23:19,683 - INFO - Types: y_test: <class 'pandas.core.frame.DataFrame'>, y_pred: <class 'numpy.ndarray'>
2024-09-26 19:23:19,683 - INFO - Model for feature 'pyr_alpha_boltz' evaluated. Test MAE: 1.7965799716777882, R²: 0.6778764232917326

model_pyr_alpha_delta.h5
pyr_alpha_delta
pyr_alpha_delta

2024-09-26 19:23:19,933 - WARNING - Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.

10/10 ━━━━━━━━━━━━━━━━━━━━ 1s 23ms/step

2024-09-26 19:23:21,323 - INFO - Shapes: y_test: (308, 190), y_pred: (308, 1)
2024-09-26 19:23:21,336 - INFO - Types: y_test: <class 'pandas.core.frame.DataFrame'>, y_pred: <class 'numpy.ndarray'>
2024-09-26 19:23:21,337 - INFO - Model for feature 'pyr_alpha_delta' evaluated. Test MAE: 1.9937548549633446, R²: 0.4128915084407937
2024-09-26 19:23:21,431 - WARNING - Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.

model_pyr_alpha_max.h5
pyr_alpha_max
pyr_alpha_max
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step

2024-09-26 19:23:21,718 - INFO - Shapes: y_test: (308, 190), y_pred: (308, 1)
2024-09-26 19:23:21,734 - INFO - Types: y_test: <class 'pandas.core.frame.DataFrame'>, y_pred: <class 'numpy.ndarray'>
2024-09-26 19:23:21,736 - INFO - Model for feature 'pyr_alpha_max' evaluated. Test MAE: 2.5482236892354773, R²: 0.5798588167937064

model_pyr_alpha_min.h5
pyr_alpha_min
pyr_alpha_min

2024-09-26 19:23:21,930 - WARNING - Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.

10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step

2024-09-26 19:23:22,441 - INFO - Shapes: y_test: (308, 190), y_pred: (308, 1)
2024-09-26 19:23:22,441 - INFO - Types: y_test: <class 'pandas.core.frame.DataFrame'>, y_pred: <class 'numpy.ndarray'>
2024-09-26 19:23:22,453 - INFO - Model for feature 'pyr_alpha_min' evaluated. Test MAE: 1.8969003381237608, R²: 0.6885104309789494

model_pyr_alpha_vburminconf.h5
pyr_alpha_vburminconf
pyr_alpha_vburminconf

2024-09-26 19:23:22,667 - WARNING - Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.

10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step

2024-09-26 19:23:23,020 - INFO - Shapes: y_test: (308, 190), y_pred: (308, 1)
2024-09-26 19:23:23,020 - INFO - Types: y_test: <class 'pandas.core.frame.DataFrame'>, y_pred: <class 'numpy.ndarray'>
2024-09-26 19:23:23,020 - INFO - Model for feature 'pyr_alpha_vburminconf' evaluated. Test MAE: 2.4475719048984153, R²: 0.585101022706334

model_pyr_P_boltz.h5
pyr_P_boltz
pyr_P_boltz

2024-09-26 19:23:23,212 - WARNING - Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.

10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step

2024-09-26 19:23:23,719 - INFO - Shapes: y_test: (308, 190), y_pred: (308, 1)
2024-09-26 19:23:23,719 - INFO - Types: y_test: <class 'pandas.core.frame.DataFrame'>, y_pred: <class 'numpy.ndarray'>
2024-09-26 19:23:23,719 - INFO - Model for feature 'pyr_P_boltz' evaluated. Test MAE: 0.027972842985798822, R²: -0.013452098225211317
2024-09-26 19:23:23,782 - WARNING - Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.

model_pyr_P_delta.h5
pyr_P_delta
pyr_P_delta
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step

2024-09-26 19:23:24,037 - INFO - Shapes: y_test: (308, 190), y_pred: (308, 1)
2024-09-26 19:23:24,037 - INFO - Types: y_test: <class 'pandas.core.frame.DataFrame'>, y_pred: <class 'numpy.ndarray'>
2024-09-26 19:23:24,037 - INFO - Model for feature 'pyr_P_delta' evaluated. Test MAE: 0.02582701975052857, R²: -0.2733474307815278

model_pyr_P_max.h5
pyr_P_max
pyr_P_max

2024-09-26 19:23:24,169 - WARNING - Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.

10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step

2024-09-26 19:23:24,576 - INFO - Shapes: y_test: (308, 190), y_pred: (308, 1)
2024-09-26 19:23:24,576 - INFO - Types: y_test: <class 'pandas.core.frame.DataFrame'>, y_pred: <class 'numpy.ndarray'>
2024-09-26 19:23:24,576 - INFO - Model for feature 'pyr_P_max' evaluated. Test MAE: 0.03209435312267561, R²: -0.4307317844489269

model_pyr_P_min.h5
pyr_P_min
pyr_P_min

2024-09-26 19:23:24,719 - WARNING - Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.

10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step

2024-09-26 19:23:25,120 - INFO - Shapes: y_test: (308, 190), y_pred: (308, 1)
2024-09-26 19:23:25,120 - INFO - Types: y_test: <class 'pandas.core.frame.DataFrame'>, y_pred: <class 'numpy.ndarray'>
2024-09-26 19:23:25,120 - INFO - Model for feature 'pyr_P_min' evaluated. Test MAE: 0.036690069962155326, R²: -0.09150592179116468

model_pyr_P_vburminconf.h5
pyr_P_vburminconf
pyr_P_vburminconf

2024-09-26 19:23:25,203 - WARNING - Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.

10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step

2024-09-26 19:23:25,498 - INFO - Shapes: y_test: (308, 190), y_pred: (308, 1)
2024-09-26 19:23:25,498 - INFO - Types: y_test: <class 'pandas.core.frame.DataFrame'>, y_pred: <class 'numpy.ndarray'>
2024-09-26 19:23:25,503 - INFO - Model for feature 'pyr_P_vburminconf' evaluated. Test MAE: 0.0348974178864863, R²: 0.011845258830998184

model_qpoletens_xx_boltz.h5
qpoletens_xx_boltz
qpoletens_xx_boltz

2024-09-26 19:23:25,586 - WARNING - Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.

10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step

2024-09-26 19:23:25,945 - INFO - Shapes: y_test: (308, 190), y_pred: (308, 1)
2024-09-26 19:23:25,945 - INFO - Types: y_test: <class 'pandas.core.frame.DataFrame'>, y_pred: <class 'numpy.ndarray'>
2024-09-26 19:23:25,953 - INFO - Model for feature 'qpoletens_xx_boltz' evaluated. Test MAE: 2.2671312883769144, R²: 0.5233050263941388

model_qpoletens_xx_delta.h5
qpoletens_xx_delta
qpoletens_xx_delta

2024-09-26 19:23:26,131 - WARNING - Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.

10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step

2024-09-26 19:23:26,503 - INFO - Shapes: y_test: (308, 190), y_pred: (308, 1)
2024-09-26 19:23:26,503 - INFO - Types: y_test: <class 'pandas.core.frame.DataFrame'>, y_pred: <class 'numpy.ndarray'>
2024-09-26 19:23:26,503 - INFO - Model for feature 'qpoletens_xx_delta' evaluated. Test MAE: 1.7524897845675147, R²: 0.5471353097029426

model_qpoletens_xx_max.h5
qpoletens_xx_max
qpoletens_xx_max

2024-09-26 19:23:26,651 - WARNING - Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.

10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step

2024-09-26 19:23:26,953 - INFO - Shapes: y_test: (308, 190), y_pred: (308, 1)
2024-09-26 19:23:26,955 - INFO - Types: y_test: <class 'pandas.core.frame.DataFrame'>, y_pred: <class 'numpy.ndarray'>
2024-09-26 19:23:26,955 - INFO - Model for feature 'qpoletens_xx_max' evaluated. Test MAE: 1.8477573420415287, R²: 0.7625802972895107

model_qpoletens_xx_min.h5
qpoletens_xx_min
qpoletens_xx_min

2024-09-26 19:23:27,099 - WARNING - Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.

10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step

2024-09-26 19:23:27,453 - INFO - Shapes: y_test: (308, 190), y_pred: (308, 1)
2024-09-26 19:23:27,453 - INFO - Types: y_test: <class 'pandas.core.frame.DataFrame'>, y_pred: <class 'numpy.ndarray'>
2024-09-26 19:23:27,453 - INFO - Model for feature 'qpoletens_xx_min' evaluated. Test MAE: 1.2193718153083954, R²: 0.6332432168438331

model_qpoletens_xx_vburminconf.h5
qpoletens_xx_vburminconf
qpoletens_xx_vburminconf

2024-09-26 19:23:27,519 - WARNING - Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.

10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step

2024-09-26 19:23:27,803 - INFO - Shapes: y_test: (308, 190), y_pred: (308, 1)
2024-09-26 19:23:27,803 - INFO - Types: y_test: <class 'pandas.core.frame.DataFrame'>, y_pred: <class 'numpy.ndarray'>
2024-09-26 19:23:27,820 - INFO - Model for feature 'qpoletens_xx_vburminconf' evaluated. Test MAE: 1.8808732447865444, R²: 0.6437580824506037

model_qpoletens_yy_boltz.h5
qpoletens_yy_boltz
qpoletens_yy_boltz

2024-09-26 19:23:27,951 - WARNING - Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.

10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step

2024-09-26 19:23:28,278 - INFO - Shapes: y_test: (308, 190), y_pred: (308, 1)
2024-09-26 19:23:28,286 - INFO - Types: y_test: <class 'pandas.core.frame.DataFrame'>, y_pred: <class 'numpy.ndarray'>
2024-09-26 19:23:28,286 - INFO - Model for feature 'qpoletens_yy_boltz' evaluated. Test MAE: 1.1023217039826716, R²: 0.10233253377196672

model_qpoletens_yy_delta.h5
qpoletens_yy_delta
qpoletens_yy_delta

2024-09-26 19:23:28,588 - WARNING - Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.

10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step

2024-09-26 19:23:29,103 - INFO - Shapes: y_test: (308, 190), y_pred: (308, 1)
2024-09-26 19:23:29,103 - INFO - Types: y_test: <class 'pandas.core.frame.DataFrame'>, y_pred: <class 'numpy.ndarray'>
2024-09-26 19:23:29,103 - INFO - Model for feature 'qpoletens_yy_delta' evaluated. Test MAE: 1.8492481653687218, R²: 0.48989278266142544
2024-09-26 19:23:29,150 - WARNING - Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.

model_qpoletens_yy_max.h5
qpoletens_yy_max
qpoletens_yy_max
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step

2024-09-26 19:23:29,396 - INFO - Shapes: y_test: (308, 190), y_pred: (308, 1)
2024-09-26 19:23:29,398 - INFO - Types: y_test: <class 'pandas.core.frame.DataFrame'>, y_pred: <class 'numpy.ndarray'>
2024-09-26 19:23:29,403 - INFO - Model for feature 'qpoletens_yy_max' evaluated. Test MAE: 1.2955151331870725, R²: 0.4756713818253925
2024-09-26 19:23:29,466 - WARNING - Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.

model_qpoletens_yy_min.h5
qpoletens_yy_min
qpoletens_yy_min
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step

2024-09-26 19:23:29,705 - INFO - Shapes: y_test: (308, 190), y_pred: (308, 1)
2024-09-26 19:23:29,705 - INFO - Types: y_test: <class 'pandas.core.frame.DataFrame'>, y_pred: <class 'numpy.ndarray'>
2024-09-26 19:23:29,705 - INFO - Model for feature 'qpoletens_yy_min' evaluated. Test MAE: 1.260741373278801, R²: 0.37575359510263295
2024-09-26 19:23:29,798 - WARNING - Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.

model_qpoletens_yy_vburminconf.h5
qpoletens_yy_vburminconf
qpoletens_yy_vburminconf
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step

2024-09-26 19:23:30,015 - INFO - Shapes: y_test: (308, 190), y_pred: (308, 1)
2024-09-26 19:23:30,015 - INFO - Types: y_test: <class 'pandas.core.frame.DataFrame'>, y_pred: <class 'numpy.ndarray'>
2024-09-26 19:23:30,030 - INFO - Model for feature 'qpoletens_yy_vburminconf' evaluated. Test MAE: 1.513144091393745, R²: 0.09720447751177919

model_qpoletens_zz_boltz.h5
qpoletens_zz_boltz
qpoletens_zz_boltz

2024-09-26 19:23:30,202 - WARNING - Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.

10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step

2024-09-26 19:23:30,669 - INFO - Shapes: y_test: (308, 190), y_pred: (308, 1)
2024-09-26 19:23:30,669 - INFO - Types: y_test: <class 'pandas.core.frame.DataFrame'>, y_pred: <class 'numpy.ndarray'>
2024-09-26 19:23:30,669 - INFO - Model for feature 'qpoletens_zz_boltz' evaluated. Test MAE: 1.5969862904429446, R²: 0.6920006422963527
2024-09-26 19:23:30,826 - WARNING - Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.

model_qpoletens_zz_delta.h5
qpoletens_zz_delta
qpoletens_zz_delta
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step

2024-09-26 19:23:31,244 - INFO - Shapes: y_test: (308, 190), y_pred: (308, 1)
2024-09-26 19:23:31,244 - INFO - Types: y_test: <class 'pandas.core.frame.DataFrame'>, y_pred: <class 'numpy.ndarray'>
2024-09-26 19:23:31,253 - INFO - Model for feature 'qpoletens_zz_delta' evaluated. Test MAE: 1.9772341519979784, R²: 0.4854669375381361

model_qpoletens_zz_max.h5
qpoletens_zz_max
qpoletens_zz_max

2024-09-26 19:23:31,402 - WARNING - Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.

10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step

2024-09-26 19:23:31,798 - INFO - Shapes: y_test: (308, 190), y_pred: (308, 1)
2024-09-26 19:23:31,798 - INFO - Types: y_test: <class 'pandas.core.frame.DataFrame'>, y_pred: <class 'numpy.ndarray'>
2024-09-26 19:23:31,813 - INFO - Model for feature 'qpoletens_zz_max' evaluated. Test MAE: 1.3706664748343673, R²: 0.5530730390883793

model_qpoletens_zz_min.h5
qpoletens_zz_min
qpoletens_zz_min

2024-09-26 19:23:31,918 - WARNING - Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.

10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step

2024-09-26 19:23:32,319 - INFO - Shapes: y_test: (308, 190), y_pred: (308, 1)
2024-09-26 19:23:32,319 - INFO - Types: y_test: <class 'pandas.core.frame.DataFrame'>, y_pred: <class 'numpy.ndarray'>
2024-09-26 19:23:32,319 - INFO - Model for feature 'qpoletens_zz_min' evaluated. Test MAE: 2.0387670472782657, R²: 0.7577969150014942

model_qpoletens_zz_vburminconf.h5
qpoletens_zz_vburminconf
qpoletens_zz_vburminconf

2024-09-26 19:23:32,571 - WARNING - Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.

10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step

2024-09-26 19:23:33,002 - INFO - Shapes: y_test: (308, 190), y_pred: (308, 1)
2024-09-26 19:23:33,002 - INFO - Types: y_test: <class 'pandas.core.frame.DataFrame'>, y_pred: <class 'numpy.ndarray'>
2024-09-26 19:23:33,002 - INFO - Model for feature 'qpoletens_zz_vburminconf' evaluated. Test MAE: 1.8700418431247414, R²: 0.6289994188187642

model_qpole_amp_boltz.h5
qpole_amp_boltz
qpole_amp_boltz

2024-09-26 19:23:33,166 - WARNING - Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.

10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step

2024-09-26 19:23:33,496 - INFO - Shapes: y_test: (308, 190), y_pred: (308, 1)
2024-09-26 19:23:33,496 - INFO - Types: y_test: <class 'pandas.core.frame.DataFrame'>, y_pred: <class 'numpy.ndarray'>
2024-09-26 19:23:33,502 - INFO - Model for feature 'qpole_amp_boltz' evaluated. Test MAE: 2.0078804004810284, R²: 0.7254243470932592

model_qpole_amp_delta.h5
qpole_amp_delta
qpole_amp_delta

2024-09-26 19:23:33,684 - WARNING - Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.

10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step

2024-09-26 19:23:34,185 - INFO - Shapes: y_test: (308, 190), y_pred: (308, 1)
2024-09-26 19:23:34,186 - INFO - Types: y_test: <class 'pandas.core.frame.DataFrame'>, y_pred: <class 'numpy.ndarray'>
2024-09-26 19:23:34,186 - INFO - Model for feature 'qpole_amp_delta' evaluated. Test MAE: 2.483079146846955, R²: 0.4557034459079612
2024-09-26 19:23:34,249 - WARNING - Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.

model_qpole_amp_max.h5
qpole_amp_max
qpole_amp_max
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step

2024-09-26 19:23:34,602 - INFO - Shapes: y_test: (308, 190), y_pred: (308, 1)
2024-09-26 19:23:34,603 - INFO - Types: y_test: <class 'pandas.core.frame.DataFrame'>, y_pred: <class 'numpy.ndarray'>
2024-09-26 19:23:34,603 - INFO - Model for feature 'qpole_amp_max' evaluated. Test MAE: 2.590615233182864, R²: 0.7525808531434105

model_qpole_amp_min.h5
qpole_amp_min
qpole_amp_min

2024-09-26 19:23:34,735 - WARNING - Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.

10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step

2024-09-26 19:23:35,069 - INFO - Shapes: y_test: (308, 190), y_pred: (308, 1)
2024-09-26 19:23:35,069 - INFO - Types: y_test: <class 'pandas.core.frame.DataFrame'>, y_pred: <class 'numpy.ndarray'>
2024-09-26 19:23:35,069 - INFO - Model for feature 'qpole_amp_min' evaluated. Test MAE: 1.8079624316828, R²: 0.629558506494793

model_qpole_amp_vburminconf.h5
qpole_amp_vburminconf
qpole_amp_vburminconf

2024-09-26 19:23:35,331 - WARNING - Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.

10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step

2024-09-26 19:23:35,752 - INFO - Shapes: y_test: (308, 190), y_pred: (308, 1)
2024-09-26 19:23:35,752 - INFO - Types: y_test: <class 'pandas.core.frame.DataFrame'>, y_pred: <class 'numpy.ndarray'>
2024-09-26 19:23:35,767 - INFO - Model for feature 'qpole_amp_vburminconf' evaluated. Test MAE: 2.6296273502514103, R²: 0.6093714973350409

model_somo_ra_boltz.h5
somo_ra_boltz
somo_ra_boltz

2024-09-26 19:23:35,912 - WARNING - Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.

10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step

2024-09-26 19:23:36,282 - INFO - Shapes: y_test: (308, 190), y_pred: (308, 1)
2024-09-26 19:23:36,298 - INFO - Types: y_test: <class 'pandas.core.frame.DataFrame'>, y_pred: <class 'numpy.ndarray'>
2024-09-26 19:23:36,298 - INFO - Model for feature 'somo_ra_boltz' evaluated. Test MAE: 0.03488287720548489, R²: -0.9722411110742328

model_somo_rc_boltz.h5
somo_rc_boltz
somo_rc_boltz

2024-09-26 19:23:36,415 - WARNING - Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.

10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step

2024-09-26 19:23:36,765 - INFO - Shapes: y_test: (308, 190), y_pred: (308, 1)
2024-09-26 19:23:36,765 - INFO - Types: y_test: <class 'pandas.core.frame.DataFrame'>, y_pred: <class 'numpy.ndarray'>
2024-09-26 19:23:36,769 - INFO - Model for feature 'somo_rc_boltz' evaluated. Test MAE: 0.05704956177031569, R²: -1.463060886073662

model_sphericity_boltz.h5
sphericity_boltz
sphericity_boltz

2024-09-26 19:23:36,946 - WARNING - Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.

10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step

2024-09-26 19:23:37,286 - INFO - Shapes: y_test: (308, 190), y_pred: (308, 1)
2024-09-26 19:23:37,286 - INFO - Types: y_test: <class 'pandas.core.frame.DataFrame'>, y_pred: <class 'numpy.ndarray'>
2024-09-26 19:23:37,286 - INFO - Model for feature 'sphericity_boltz' evaluated. Test MAE: 0.025763357022296065, R²: 0.6700538658806743

model_spindens_P_ra_boltz.h5
spindens_P_ra_boltz
spindens_P_ra_boltz

2024-09-26 19:23:37,560 - WARNING - Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.

10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step

2024-09-26 19:23:38,053 - INFO - Shapes: y_test: (308, 190), y_pred: (308, 1)
2024-09-26 19:23:38,053 - INFO - Types: y_test: <class 'pandas.core.frame.DataFrame'>, y_pred: <class 'numpy.ndarray'>
2024-09-26 19:23:38,053 - INFO - Model for feature 'spindens_P_ra_boltz' evaluated. Test MAE: 0.04005135354263421, R²: 0.5280322995143193

model_spindens_P_rc_boltz.h5
spindens_P_rc_boltz
spindens_P_rc_boltz

2024-09-26 19:23:38,269 - WARNING - Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.

10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step

2024-09-26 19:23:38,702 - INFO - Shapes: y_test: (308, 190), y_pred: (308, 1)
2024-09-26 19:23:38,702 - INFO - Types: y_test: <class 'pandas.core.frame.DataFrame'>, y_pred: <class 'numpy.ndarray'>
2024-09-26 19:23:38,702 - INFO - Model for feature 'spindens_P_rc_boltz' evaluated. Test MAE: 0.1958641091536936, R²: 0.035964353384638326

model_sterimol_B1_boltz.h5
sterimol_B1_boltz
sterimol_B1_boltz

2024-09-26 19:23:38,784 - WARNING - Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.

10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step

2024-09-26 19:23:39,098 - INFO - Shapes: y_test: (308, 190), y_pred: (308, 1)
2024-09-26 19:23:39,098 - INFO - Types: y_test: <class 'pandas.core.frame.DataFrame'>, y_pred: <class 'numpy.ndarray'>
2024-09-26 19:23:39,114 - INFO - Model for feature 'sterimol_B1_boltz' evaluated. Test MAE: 0.34178812579647155, R²: 0.6574135235508922

model_sterimol_B1_delta.h5
sterimol_B1_delta
sterimol_B1_delta

2024-09-26 19:23:39,234 - WARNING - Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.

10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step

2024-09-26 19:23:39,636 - INFO - Shapes: y_test: (308, 190), y_pred: (308, 1)
2024-09-26 19:23:39,636 - INFO - Types: y_test: <class 'pandas.core.frame.DataFrame'>, y_pred: <class 'numpy.ndarray'>
2024-09-26 19:23:39,636 - INFO - Model for feature 'sterimol_B1_delta' evaluated. Test MAE: 0.3262646066037752, R²: 0.5708765740335816

model_sterimol_B1_max.h5
sterimol_B1_max
sterimol_B1_max

2024-09-26 19:23:39,882 - WARNING - Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.

10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step

2024-09-26 19:23:40,390 - INFO - Shapes: y_test: (308, 190), y_pred: (308, 1)
2024-09-26 19:23:40,390 - INFO - Types: y_test: <class 'pandas.core.frame.DataFrame'>, y_pred: <class 'numpy.ndarray'>
2024-09-26 19:23:40,401 - INFO - Model for feature 'sterimol_B1_max' evaluated. Test MAE: 0.39859401041193104, R²: 0.5935716365360546
2024-09-26 19:23:40,465 - WARNING - Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.

model_sterimol_B1_min.h5
sterimol_B1_min
sterimol_B1_min
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step

2024-09-26 19:23:40,802 - INFO - Shapes: y_test: (308, 190), y_pred: (308, 1)
2024-09-26 19:23:40,802 - INFO - Types: y_test: <class 'pandas.core.frame.DataFrame'>, y_pred: <class 'numpy.ndarray'>
2024-09-26 19:23:40,802 - INFO - Model for feature 'sterimol_B1_min' evaluated. Test MAE: 0.3098218951896854, R²: 0.7442165784110195

model_sterimol_B1_vburminconf.h5
sterimol_B1_vburminconf
sterimol_B1_vburminconf

2024-09-26 19:23:41,068 - WARNING - Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.

10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step

2024-09-26 19:23:41,585 - INFO - Shapes: y_test: (308, 190), y_pred: (308, 1)
2024-09-26 19:23:41,585 - INFO - Types: y_test: <class 'pandas.core.frame.DataFrame'>, y_pred: <class 'numpy.ndarray'>
2024-09-26 19:23:41,585 - INFO - Model for feature 'sterimol_B1_vburminconf' evaluated. Test MAE: 0.4302825643939328, R²: 0.5352028127222108
2024-09-26 19:23:41,764 - WARNING - Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.

model_sterimol_B5_boltz.h5
sterimol_B5_boltz
sterimol_B5_boltz
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step

2024-09-26 19:23:43,084 - INFO - Shapes: y_test: (308, 190), y_pred: (308, 1)
2024-09-26 19:23:43,084 - INFO - Types: y_test: <class 'pandas.core.frame.DataFrame'>, y_pred: <class 'numpy.ndarray'>
2024-09-26 19:23:43,084 - INFO - Model for feature 'sterimol_B5_boltz' evaluated. Test MAE: 0.9177999783974375, R²: 0.37920303678299894

model_sterimol_B5_delta.h5
sterimol_B5_delta
sterimol_B5_delta

2024-09-26 19:23:43,296 - WARNING - Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.

10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step

2024-09-26 19:23:43,679 - INFO - Shapes: y_test: (308, 190), y_pred: (308, 1)
2024-09-26 19:23:43,685 - INFO - Types: y_test: <class 'pandas.core.frame.DataFrame'>, y_pred: <class 'numpy.ndarray'>
2024-09-26 19:23:43,686 - INFO - Model for feature 'sterimol_B5_delta' evaluated. Test MAE: 0.7338903461686862, R²: 0.14378525718171287

model_sterimol_B5_max.h5
sterimol_B5_max
sterimol_B5_max

2024-09-26 19:23:43,865 - WARNING - Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.

10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step

2024-09-26 19:23:44,202 - INFO - Shapes: y_test: (308, 190), y_pred: (308, 1)
2024-09-26 19:23:44,202 - INFO - Types: y_test: <class 'pandas.core.frame.DataFrame'>, y_pred: <class 'numpy.ndarray'>
2024-09-26 19:23:44,202 - INFO - Model for feature 'sterimol_B5_max' evaluated. Test MAE: 0.7794894295464665, R²: 0.5980044465845293

model_sterimol_B5_min.h5
sterimol_B5_min
sterimol_B5_min

2024-09-26 19:23:44,473 - WARNING - Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.

10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step

2024-09-26 19:23:44,910 - INFO - Shapes: y_test: (308, 190), y_pred: (308, 1)
2024-09-26 19:23:44,910 - INFO - Types: y_test: <class 'pandas.core.frame.DataFrame'>, y_pred: <class 'numpy.ndarray'>
2024-09-26 19:23:44,919 - INFO - Model for feature 'sterimol_B5_min' evaluated. Test MAE: 0.588754901184648, R²: 0.6860378375447005
2024-09-26 19:23:44,997 - WARNING - Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.

model_sterimol_B5_vburminconf.h5
sterimol_B5_vburminconf
sterimol_B5_vburminconf
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step

2024-09-26 19:23:45,251 - INFO - Shapes: y_test: (308, 190), y_pred: (308, 1)
2024-09-26 19:23:45,251 - INFO - Types: y_test: <class 'pandas.core.frame.DataFrame'>, y_pred: <class 'numpy.ndarray'>
2024-09-26 19:23:45,251 - INFO - Model for feature 'sterimol_B5_vburminconf' evaluated. Test MAE: 0.6069354038977717, R²: 0.7099211556524152
2024-09-26 19:23:45,334 - WARNING - Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.

model_sterimol_burB1_boltz.h5
sterimol_burB1_boltz
sterimol_burB1_boltz
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step

2024-09-26 19:23:45,764 - INFO - Shapes: y_test: (308, 190), y_pred: (308, 1)
2024-09-26 19:23:45,764 - INFO - Types: y_test: <class 'pandas.core.frame.DataFrame'>, y_pred: <class 'numpy.ndarray'>
2024-09-26 19:23:45,768 - INFO - Model for feature 'sterimol_burB1_boltz' evaluated. Test MAE: 0.31037299725182393, R²: 0.5494517167409696

model_sterimol_burB1_delta.h5
sterimol_burB1_delta
sterimol_burB1_delta

2024-09-26 19:23:46,008 - WARNING - Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.

10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step

2024-09-26 19:23:46,435 - INFO - Shapes: y_test: (308, 190), y_pred: (308, 1)
2024-09-26 19:23:46,435 - INFO - Types: y_test: <class 'pandas.core.frame.DataFrame'>, y_pred: <class 'numpy.ndarray'>
2024-09-26 19:23:46,435 - INFO - Model for feature 'sterimol_burB1_delta' evaluated. Test MAE: 0.29390314992693506, R²: 0.5167579922314769
2024-09-26 19:23:46,561 - WARNING - Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.

model_sterimol_burB1_max.h5
sterimol_burB1_max
sterimol_burB1_max
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step

2024-09-26 19:23:46,878 - INFO - Shapes: y_test: (308, 190), y_pred: (308, 1)
2024-09-26 19:23:46,878 - INFO - Types: y_test: <class 'pandas.core.frame.DataFrame'>, y_pred: <class 'numpy.ndarray'>
2024-09-26 19:23:46,885 - INFO - Model for feature 'sterimol_burB1_max' evaluated. Test MAE: 0.2857780153575221, R²: 0.6575167988425948

model_sterimol_burB1_min.h5
sterimol_burB1_min
sterimol_burB1_min

2024-09-26 19:23:46,984 - WARNING - Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.

10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step

2024-09-26 19:23:47,295 - INFO - Shapes: y_test: (308, 190), y_pred: (308, 1)
2024-09-26 19:23:47,295 - INFO - Types: y_test: <class 'pandas.core.frame.DataFrame'>, y_pred: <class 'numpy.ndarray'>
2024-09-26 19:23:47,295 - INFO - Model for feature 'sterimol_burB1_min' evaluated. Test MAE: 0.2949945329506594, R²: 0.6260761522049354

model_sterimol_burB1_vburminconf.h5
sterimol_burB1_vburminconf
sterimol_burB1_vburminconf

2024-09-26 19:23:47,416 - WARNING - Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.

10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step

2024-09-26 19:23:47,842 - INFO - Shapes: y_test: (308, 190), y_pred: (308, 1)
2024-09-26 19:23:47,842 - INFO - Types: y_test: <class 'pandas.core.frame.DataFrame'>, y_pred: <class 'numpy.ndarray'>
2024-09-26 19:23:47,842 - INFO - Model for feature 'sterimol_burB1_vburminconf' evaluated. Test MAE: 0.29916889804165886, R²: 0.5765085039788602

model_sterimol_burB5_boltz.h5
sterimol_burB5_boltz
sterimol_burB5_boltz

2024-09-26 19:23:48,130 - WARNING - Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.

10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step

2024-09-26 19:23:48,626 - INFO - Shapes: y_test: (308, 190), y_pred: (308, 1)
2024-09-26 19:23:48,626 - INFO - Types: y_test: <class 'pandas.core.frame.DataFrame'>, y_pred: <class 'numpy.ndarray'>
2024-09-26 19:23:48,642 - INFO - Model for feature 'sterimol_burB5_boltz' evaluated. Test MAE: 0.6514197401666189, R²: -0.28154959401382107
2024-09-26 19:23:48,763 - WARNING - Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.

model_sterimol_burB5_delta.h5
sterimol_burB5_delta
sterimol_burB5_delta
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step

2024-09-26 19:23:49,068 - INFO - Shapes: y_test: (308, 190), y_pred: (308, 1)
2024-09-26 19:23:49,068 - INFO - Types: y_test: <class 'pandas.core.frame.DataFrame'>, y_pred: <class 'numpy.ndarray'>
2024-09-26 19:23:49,068 - INFO - Model for feature 'sterimol_burB5_delta' evaluated. Test MAE: 0.32734815143295404, R²: 0.4474651842204489

model_sterimol_burB5_max.h5
sterimol_burB5_max
sterimol_burB5_max

2024-09-26 19:23:49,151 - WARNING - Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.

10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step

2024-09-26 19:23:49,468 - INFO - Shapes: y_test: (308, 190), y_pred: (308, 1)
2024-09-26 19:23:49,468 - INFO - Types: y_test: <class 'pandas.core.frame.DataFrame'>, y_pred: <class 'numpy.ndarray'>
2024-09-26 19:23:49,468 - INFO - Model for feature 'sterimol_burB5_max' evaluated. Test MAE: 0.4219500353219961, R²: 0.5643104115442374
2024-09-26 19:23:49,552 - WARNING - Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.

model_sterimol_burB5_min.h5
sterimol_burB5_min
sterimol_burB5_min
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 6ms/step

2024-09-26 19:23:49,798 - INFO - Shapes: y_test: (308, 190), y_pred: (308, 1)
2024-09-26 19:23:49,798 - INFO - Types: y_test: <class 'pandas.core.frame.DataFrame'>, y_pred: <class 'numpy.ndarray'>
2024-09-26 19:23:49,815 - INFO - Model for feature 'sterimol_burB5_min' evaluated. Test MAE: 0.43618556870355385, R²: 0.432811644691117
2024-09-26 19:23:49,930 - WARNING - Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.

model_sterimol_burB5_vburminconf.h5
sterimol_burB5_vburminconf
sterimol_burB5_vburminconf
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step

2024-09-26 19:23:50,212 - INFO - Shapes: y_test: (308, 190), y_pred: (308, 1)
2024-09-26 19:23:50,212 - INFO - Types: y_test: <class 'pandas.core.frame.DataFrame'>, y_pred: <class 'numpy.ndarray'>
2024-09-26 19:23:50,228 - INFO - Model for feature 'sterimol_burB5_vburminconf' evaluated. Test MAE: 0.4692434390570393, R²: 0.3930793442668521
2024-09-26 19:23:50,281 - WARNING - Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.

model_sterimol_burL_boltz.h5
sterimol_burL_boltz
sterimol_burL_boltz
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step

2024-09-26 19:23:50,568 - INFO - Shapes: y_test: (308, 190), y_pred: (308, 1)
2024-09-26 19:23:50,568 - INFO - Types: y_test: <class 'pandas.core.frame.DataFrame'>, y_pred: <class 'numpy.ndarray'>
2024-09-26 19:23:50,585 - INFO - Model for feature 'sterimol_burL_boltz' evaluated. Test MAE: 0.22736603456711096, R²: 0.3206202476780101

model_sterimol_burL_delta.h5
sterimol_burL_delta
sterimol_burL_delta

2024-09-26 19:23:50,763 - WARNING - Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.

10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step

2024-09-26 19:23:51,251 - INFO - Shapes: y_test: (308, 190), y_pred: (308, 1)
2024-09-26 19:23:51,251 - INFO - Types: y_test: <class 'pandas.core.frame.DataFrame'>, y_pred: <class 'numpy.ndarray'>
2024-09-26 19:23:51,251 - INFO - Model for feature 'sterimol_burL_delta' evaluated. Test MAE: 0.293477806464035, R²: 0.6086422069648447
2024-09-26 19:23:51,377 - WARNING - Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.

model_sterimol_burL_max.h5
sterimol_burL_max
sterimol_burL_max
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step

2024-09-26 19:23:51,734 - INFO - Shapes: y_test: (308, 190), y_pred: (308, 1)
2024-09-26 19:23:51,734 - INFO - Types: y_test: <class 'pandas.core.frame.DataFrame'>, y_pred: <class 'numpy.ndarray'>
2024-09-26 19:23:51,734 - INFO - Model for feature 'sterimol_burL_max' evaluated. Test MAE: 0.27668181706926226, R²: 0.3655859667620657

model_sterimol_burL_min.h5
sterimol_burL_min
sterimol_burL_min

2024-09-26 19:23:51,947 - WARNING - Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.

10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step

2024-09-26 19:23:52,401 - INFO - Shapes: y_test: (308, 190), y_pred: (308, 1)
2024-09-26 19:23:52,401 - INFO - Types: y_test: <class 'pandas.core.frame.DataFrame'>, y_pred: <class 'numpy.ndarray'>
2024-09-26 19:23:52,401 - INFO - Model for feature 'sterimol_burL_min' evaluated. Test MAE: 0.2225661090834557, R²: 0.6640820132806571

model_sterimol_burL_vburminconf.h5
sterimol_burL_vburminconf
sterimol_burL_vburminconf

2024-09-26 19:23:52,484 - WARNING - Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.

10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step

2024-09-26 19:23:52,834 - INFO - Shapes: y_test: (308, 190), y_pred: (308, 1)
2024-09-26 19:23:52,834 - INFO - Types: y_test: <class 'pandas.core.frame.DataFrame'>, y_pred: <class 'numpy.ndarray'>
2024-09-26 19:23:52,834 - INFO - Model for feature 'sterimol_burL_vburminconf' evaluated. Test MAE: 0.343314505653528, R²: -0.3599345919619683
2024-09-26 19:23:52,898 - WARNING - Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.

model_sterimol_L_boltz.h5
sterimol_L_boltz
sterimol_L_boltz
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step

2024-09-26 19:23:53,251 - INFO - Shapes: y_test: (308, 190), y_pred: (308, 1)
2024-09-26 19:23:53,251 - INFO - Types: y_test: <class 'pandas.core.frame.DataFrame'>, y_pred: <class 'numpy.ndarray'>
2024-09-26 19:23:53,251 - INFO - Model for feature 'sterimol_L_boltz' evaluated. Test MAE: 0.6220583721967631, R²: 0.5401678477645477

model_sterimol_L_delta.h5
sterimol_L_delta
sterimol_L_delta

2024-09-26 19:23:53,413 - WARNING - Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.

10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step

2024-09-26 19:23:53,817 - INFO - Shapes: y_test: (308, 190), y_pred: (308, 1)
2024-09-26 19:23:53,817 - INFO - Types: y_test: <class 'pandas.core.frame.DataFrame'>, y_pred: <class 'numpy.ndarray'>
2024-09-26 19:23:53,817 - INFO - Model for feature 'sterimol_L_delta' evaluated. Test MAE: 0.7427943840873309, R²: 0.5822240150777596

model_sterimol_L_max.h5
sterimol_L_max
sterimol_L_max

2024-09-26 19:23:54,027 - WARNING - Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.

10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step

2024-09-26 19:23:54,483 - INFO - Shapes: y_test: (308, 190), y_pred: (308, 1)
2024-09-26 19:23:54,484 - INFO - Types: y_test: <class 'pandas.core.frame.DataFrame'>, y_pred: <class 'numpy.ndarray'>
2024-09-26 19:23:54,484 - INFO - Model for feature 'sterimol_L_max' evaluated. Test MAE: 0.8695506186354545, R²: 0.4580024892567559
2024-09-26 19:23:54,641 - WARNING - Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.

model_sterimol_L_min.h5
sterimol_L_min
sterimol_L_min
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step

2024-09-26 19:23:55,095 - INFO - Shapes: y_test: (308, 190), y_pred: (308, 1)
2024-09-26 19:23:55,095 - INFO - Types: y_test: <class 'pandas.core.frame.DataFrame'>, y_pred: <class 'numpy.ndarray'>
2024-09-26 19:23:55,101 - INFO - Model for feature 'sterimol_L_min' evaluated. Test MAE: 0.47256079881412344, R²: 0.6570926393553308
2024-09-26 19:23:55,226 - WARNING - Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.

model_sterimol_L_vburminconf.h5
sterimol_L_vburminconf
sterimol_L_vburminconf
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step

2024-09-26 19:23:55,577 - INFO - Shapes: y_test: (308, 190), y_pred: (308, 1)
2024-09-26 19:23:55,577 - INFO - Types: y_test: <class 'pandas.core.frame.DataFrame'>, y_pred: <class 'numpy.ndarray'>
2024-09-26 19:23:55,584 - INFO - Model for feature 'sterimol_L_vburminconf' evaluated. Test MAE: 0.8521708269442995, R²: 0.43829275109816934

model_surface_area_boltz.h5
surface_area_boltz
surface_area_boltz

2024-09-26 19:23:55,824 - WARNING - Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.

10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step

2024-09-26 19:23:56,272 - INFO - Shapes: y_test: (308, 190), y_pred: (308, 1)
2024-09-26 19:23:56,284 - INFO - Types: y_test: <class 'pandas.core.frame.DataFrame'>, y_pred: <class 'numpy.ndarray'>
2024-09-26 19:23:56,284 - INFO - Model for feature 'surface_area_boltz' evaluated. Test MAE: 41.426413299752696, R²: 0.7624930870821693

model_vbur_far_vbur_boltz.h5
vbur_far_vbur_boltz
vbur_far_vbur_boltz

2024-09-26 19:23:56,531 - WARNING - Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.

10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step

2024-09-26 19:23:56,968 - INFO - Shapes: y_test: (308, 190), y_pred: (308, 1)
2024-09-26 19:23:56,968 - INFO - Types: y_test: <class 'pandas.core.frame.DataFrame'>, y_pred: <class 'numpy.ndarray'>
2024-09-26 19:23:56,968 - INFO - Model for feature 'vbur_far_vbur_boltz' evaluated. Test MAE: 6.165290481978841, R²: -0.2068603089342591

model_vbur_far_vbur_delta.h5
vbur_far_vbur_delta
vbur_far_vbur_delta

2024-09-26 19:23:57,199 - WARNING - Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.

10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step

2024-09-26 19:23:57,657 - INFO - Shapes: y_test: (308, 190), y_pred: (308, 1)
2024-09-26 19:23:57,657 - INFO - Types: y_test: <class 'pandas.core.frame.DataFrame'>, y_pred: <class 'numpy.ndarray'>
2024-09-26 19:23:57,657 - INFO - Model for feature 'vbur_far_vbur_delta' evaluated. Test MAE: 5.227871722147237, R²: 0.5295607283152535

model_vbur_far_vbur_max.h5
vbur_far_vbur_max
vbur_far_vbur_max

2024-09-26 19:23:57,850 - WARNING - Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.

10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step

2024-09-26 19:23:58,210 - INFO - Shapes: y_test: (308, 190), y_pred: (308, 1)
2024-09-26 19:23:58,210 - INFO - Types: y_test: <class 'pandas.core.frame.DataFrame'>, y_pred: <class 'numpy.ndarray'>
2024-09-26 19:23:58,210 - INFO - Model for feature 'vbur_far_vbur_max' evaluated. Test MAE: 5.067866271895488, R²: 0.6694150588542367

model_vbur_far_vbur_min.h5
vbur_far_vbur_min
vbur_far_vbur_min

2024-09-26 19:23:58,489 - WARNING - Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.

10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step

2024-09-26 19:23:59,033 - INFO - Shapes: y_test: (308, 190), y_pred: (308, 1)
2024-09-26 19:23:59,034 - INFO - Types: y_test: <class 'pandas.core.frame.DataFrame'>, y_pred: <class 'numpy.ndarray'>
2024-09-26 19:23:59,034 - INFO - Model for feature 'vbur_far_vbur_min' evaluated. Test MAE: 2.209854055133739, R²: -0.09340411528229065
2024-09-26 19:23:59,116 - WARNING - Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.

model_vbur_far_vbur_vburminconf.h5
vbur_far_vbur_vburminconf
vbur_far_vbur_vburminconf
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 7ms/step

2024-09-26 19:23:59,384 - INFO - Shapes: y_test: (308, 190), y_pred: (308, 1)
2024-09-26 19:23:59,384 - INFO - Types: y_test: <class 'pandas.core.frame.DataFrame'>, y_pred: <class 'numpy.ndarray'>
2024-09-26 19:23:59,384 - INFO - Model for feature 'vbur_far_vbur_vburminconf' evaluated. Test MAE: 1.9971608286008913, R²: 0.09280710236562006

model_vbur_far_vtot_boltz.h5
vbur_far_vtot_boltz
vbur_far_vtot_boltz

2024-09-26 19:23:59,517 - WARNING - Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.

10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step

2024-09-26 19:23:59,982 - INFO - Shapes: y_test: (308, 190), y_pred: (308, 1)
2024-09-26 19:23:59,982 - INFO - Types: y_test: <class 'pandas.core.frame.DataFrame'>, y_pred: <class 'numpy.ndarray'>
2024-09-26 19:23:59,982 - INFO - Model for feature 'vbur_far_vtot_boltz' evaluated. Test MAE: 12.534557292541523, R²: 0.5685670079185934

model_vbur_far_vtot_delta.h5
vbur_far_vtot_delta
vbur_far_vtot_delta

2024-09-26 19:24:00,081 - WARNING - Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.

10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step

2024-09-26 19:24:00,384 - INFO - Shapes: y_test: (308, 190), y_pred: (308, 1)
2024-09-26 19:24:00,384 - INFO - Types: y_test: <class 'pandas.core.frame.DataFrame'>, y_pred: <class 'numpy.ndarray'>
2024-09-26 19:24:00,384 - INFO - Model for feature 'vbur_far_vtot_delta' evaluated. Test MAE: 13.82444297536976, R²: 0.5927350191785203

model_vbur_far_vtot_max.h5
vbur_far_vtot_max
vbur_far_vtot_max

2024-09-26 19:24:00,578 - WARNING - Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.

10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step

2024-09-26 19:24:00,973 - INFO - Shapes: y_test: (308, 190), y_pred: (308, 1)
2024-09-26 19:24:00,973 - INFO - Types: y_test: <class 'pandas.core.frame.DataFrame'>, y_pred: <class 'numpy.ndarray'>
2024-09-26 19:24:00,984 - INFO - Model for feature 'vbur_far_vtot_max' evaluated. Test MAE: 13.965282503926657, R²: 0.6662227266867692

model_vbur_far_vtot_min.h5
vbur_far_vtot_min
vbur_far_vtot_min

2024-09-26 19:24:01,161 - WARNING - Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.

10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step

2024-09-26 19:24:01,641 - INFO - Shapes: y_test: (308, 190), y_pred: (308, 1)
2024-09-26 19:24:01,656 - INFO - Types: y_test: <class 'pandas.core.frame.DataFrame'>, y_pred: <class 'numpy.ndarray'>
2024-09-26 19:24:01,656 - INFO - Model for feature 'vbur_far_vtot_min' evaluated. Test MAE: 6.7907700153351715, R²: 0.13313461173805896

model_vbur_far_vtot_vburminconf.h5
vbur_far_vtot_vburminconf
vbur_far_vtot_vburminconf

2024-09-26 19:24:01,907 - WARNING - Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.

10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step

2024-09-26 19:24:02,408 - INFO - Shapes: y_test: (308, 190), y_pred: (308, 1)
2024-09-26 19:24:02,408 - INFO - Types: y_test: <class 'pandas.core.frame.DataFrame'>, y_pred: <class 'numpy.ndarray'>
2024-09-26 19:24:02,417 - INFO - Model for feature 'vbur_far_vtot_vburminconf' evaluated. Test MAE: 7.359747146845671, R²: 0.12355767234910309

model_vbur_max_delta_qvbur_boltz.h5
vbur_max_delta_qvbur_boltz
vbur_max_delta_qvbur_boltz

2024-09-26 19:24:02,617 - WARNING - Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.

10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step

2024-09-26 19:24:03,025 - INFO - Shapes: y_test: (308, 190), y_pred: (308, 1)
2024-09-26 19:24:03,025 - INFO - Types: y_test: <class 'pandas.core.frame.DataFrame'>, y_pred: <class 'numpy.ndarray'>
2024-09-26 19:24:03,025 - INFO - Model for feature 'vbur_max_delta_qvbur_boltz' evaluated. Test MAE: 2.3529018355702327, R²: 0.7459156690527123

model_vbur_max_delta_qvbur_delta.h5
vbur_max_delta_qvbur_delta
vbur_max_delta_qvbur_delta

2024-09-26 19:24:03,210 - WARNING - Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.

10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step

2024-09-26 19:24:03,584 - INFO - Shapes: y_test: (308, 190), y_pred: (308, 1)
2024-09-26 19:24:03,584 - INFO - Types: y_test: <class 'pandas.core.frame.DataFrame'>, y_pred: <class 'numpy.ndarray'>
2024-09-26 19:24:03,584 - INFO - Model for feature 'vbur_max_delta_qvbur_delta' evaluated. Test MAE: 3.149245808985027, R²: 0.624061869761653

model_vbur_max_delta_qvbur_max.h5
vbur_max_delta_qvbur_max
vbur_max_delta_qvbur_max

2024-09-26 19:24:03,700 - WARNING - Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.

10/10 ━━━━━━━━━━━━━━━━━━━━ 1s 110ms/step

2024-09-26 19:24:04,917 - INFO - Shapes: y_test: (308, 190), y_pred: (308, 1)
2024-09-26 19:24:04,917 - INFO - Types: y_test: <class 'pandas.core.frame.DataFrame'>, y_pred: <class 'numpy.ndarray'>
2024-09-26 19:24:04,917 - INFO - Model for feature 'vbur_max_delta_qvbur_max' evaluated. Test MAE: 3.0526961403596267, R²: 0.7267789742673246
2024-09-26 19:24:05,096 - WARNING - Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.

model_vbur_max_delta_qvbur_min.h5
vbur_max_delta_qvbur_min
vbur_max_delta_qvbur_min
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step

2024-09-26 19:24:05,576 - INFO - Shapes: y_test: (308, 190), y_pred: (308, 1)
2024-09-26 19:24:05,576 - INFO - Types: y_test: <class 'pandas.core.frame.DataFrame'>, y_pred: <class 'numpy.ndarray'>
2024-09-26 19:24:05,583 - INFO - Model for feature 'vbur_max_delta_qvbur_min' evaluated. Test MAE: 2.0228866723645624, R²: 0.32757789529722947

model_vbur_max_delta_qvbur_vburminconf.h5
vbur_max_delta_qvbur_vburminconf
vbur_max_delta_qvbur_vburminconf

2024-09-26 19:24:05,831 - WARNING - Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.

10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step

2024-09-26 19:24:06,343 - INFO - Shapes: y_test: (308, 190), y_pred: (308, 1)
2024-09-26 19:24:06,343 - INFO - Types: y_test: <class 'pandas.core.frame.DataFrame'>, y_pred: <class 'numpy.ndarray'>
2024-09-26 19:24:06,343 - INFO - Model for feature 'vbur_max_delta_qvbur_vburminconf' evaluated. Test MAE: 2.3644756293112335, R²: 0.27940873067466265
2024-09-26 19:24:06,444 - WARNING - Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.

model_vbur_max_delta_qvtot_boltz.h5
vbur_max_delta_qvtot_boltz
vbur_max_delta_qvtot_boltz
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step

2024-09-26 19:24:06,716 - INFO - Shapes: y_test: (308, 190), y_pred: (308, 1)
2024-09-26 19:24:06,717 - INFO - Types: y_test: <class 'pandas.core.frame.DataFrame'>, y_pred: <class 'numpy.ndarray'>
2024-09-26 19:24:06,717 - INFO - Model for feature 'vbur_max_delta_qvtot_boltz' evaluated. Test MAE: 19.11099949489475, R²: 0.6945726711174816

model_vbur_max_delta_qvtot_delta.h5
vbur_max_delta_qvtot_delta
vbur_max_delta_qvtot_delta

2024-09-26 19:24:06,941 - WARNING - Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.

10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 17ms/step

2024-09-26 19:24:07,383 - INFO - Shapes: y_test: (308, 190), y_pred: (308, 1)
2024-09-26 19:24:07,399 - INFO - Types: y_test: <class 'pandas.core.frame.DataFrame'>, y_pred: <class 'numpy.ndarray'>
2024-09-26 19:24:07,400 - INFO - Model for feature 'vbur_max_delta_qvtot_delta' evaluated. Test MAE: 19.840007711257435, R²: 0.5301175552260576

model_vbur_max_delta_qvtot_max.h5
vbur_max_delta_qvtot_max
vbur_max_delta_qvtot_max

2024-09-26 19:24:07,497 - WARNING - Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.

10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 10ms/step

2024-09-26 19:24:07,817 - INFO - Shapes: y_test: (308, 190), y_pred: (308, 1)
2024-09-26 19:24:07,817 - INFO - Types: y_test: <class 'pandas.core.frame.DataFrame'>, y_pred: <class 'numpy.ndarray'>
2024-09-26 19:24:07,817 - INFO - Model for feature 'vbur_max_delta_qvtot_max' evaluated. Test MAE: 22.508996592281253, R²: 0.662748143629882

model_vbur_max_delta_qvtot_min.h5
vbur_max_delta_qvtot_min
vbur_max_delta_qvtot_min

2024-09-26 19:24:07,932 - WARNING - Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.

10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step

2024-09-26 19:24:08,292 - INFO - Shapes: y_test: (308, 190), y_pred: (308, 1)
2024-09-26 19:24:08,292 - INFO - Types: y_test: <class 'pandas.core.frame.DataFrame'>, y_pred: <class 'numpy.ndarray'>
2024-09-26 19:24:08,292 - INFO - Model for feature 'vbur_max_delta_qvtot_min' evaluated. Test MAE: 17.90902103210791, R²: 0.59665549100859

model_vbur_max_delta_qvtot_vburminconf.h5
vbur_max_delta_qvtot_vburminconf
vbur_max_delta_qvtot_vburminconf

2024-09-26 19:24:08,430 - WARNING - Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.

10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step

2024-09-26 19:24:08,783 - INFO - Shapes: y_test: (308, 190), y_pred: (308, 1)
2024-09-26 19:24:08,783 - INFO - Types: y_test: <class 'pandas.core.frame.DataFrame'>, y_pred: <class 'numpy.ndarray'>
2024-09-26 19:24:08,783 - INFO - Model for feature 'vbur_max_delta_qvtot_vburminconf' evaluated. Test MAE: 21.592409741637425, R²: 0.5644867282202708

model_vbur_near_vbur_boltz.h5
vbur_near_vbur_boltz
vbur_near_vbur_boltz

2024-09-26 19:24:08,946 - WARNING - Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.

10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step

2024-09-26 19:24:09,292 - INFO - Shapes: y_test: (308, 190), y_pred: (308, 1)
2024-09-26 19:24:09,292 - INFO - Types: y_test: <class 'pandas.core.frame.DataFrame'>, y_pred: <class 'numpy.ndarray'>
2024-09-26 19:24:09,308 - INFO - Model for feature 'vbur_near_vbur_boltz' evaluated. Test MAE: 4.103186750655438, R²: 0.6641542471433477

model_vbur_near_vbur_delta.h5
vbur_near_vbur_delta
vbur_near_vbur_delta

2024-09-26 19:24:09,415 - WARNING - Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.

10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step

2024-09-26 19:24:09,718 - INFO - Shapes: y_test: (308, 190), y_pred: (308, 1)
2024-09-26 19:24:09,718 - INFO - Types: y_test: <class 'pandas.core.frame.DataFrame'>, y_pred: <class 'numpy.ndarray'>
2024-09-26 19:24:09,718 - INFO - Model for feature 'vbur_near_vbur_delta' evaluated. Test MAE: 3.0718879675135535, R²: 0.6971789303459934

model_vbur_near_vbur_max.h5
vbur_near_vbur_max
vbur_near_vbur_max

2024-09-26 19:24:09,879 - WARNING - Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.

10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step

2024-09-26 19:24:10,282 - INFO - Shapes: y_test: (308, 190), y_pred: (308, 1)
2024-09-26 19:24:10,283 - INFO - Types: y_test: <class 'pandas.core.frame.DataFrame'>, y_pred: <class 'numpy.ndarray'>
2024-09-26 19:24:10,283 - INFO - Model for feature 'vbur_near_vbur_max' evaluated. Test MAE: 4.115021125438534, R²: 0.7425206124683075

model_vbur_near_vbur_min.h5
vbur_near_vbur_min
vbur_near_vbur_min

2024-09-26 19:24:10,443 - WARNING - Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.

10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step

2024-09-26 19:24:10,801 - INFO - Shapes: y_test: (308, 190), y_pred: (308, 1)
2024-09-26 19:24:10,816 - INFO - Types: y_test: <class 'pandas.core.frame.DataFrame'>, y_pred: <class 'numpy.ndarray'>
2024-09-26 19:24:10,817 - INFO - Model for feature 'vbur_near_vbur_min' evaluated. Test MAE: 3.0138762071158434, R²: 0.7722794606940636

model_vbur_near_vbur_vburminconf.h5
vbur_near_vbur_vburminconf
vbur_near_vbur_vburminconf

2024-09-26 19:24:11,001 - WARNING - Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.

10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step

2024-09-26 19:24:11,450 - INFO - Shapes: y_test: (308, 190), y_pred: (308, 1)
2024-09-26 19:24:11,450 - INFO - Types: y_test: <class 'pandas.core.frame.DataFrame'>, y_pred: <class 'numpy.ndarray'>
2024-09-26 19:24:11,450 - INFO - Model for feature 'vbur_near_vbur_vburminconf' evaluated. Test MAE: 3.3699902786681974, R²: 0.7207182199360996

model_vbur_near_vtot_boltz.h5
vbur_near_vtot_boltz
vbur_near_vtot_boltz

2024-09-26 19:24:11,733 - WARNING - Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.

10/10 ━━━━━━━━━━━━━━━━━━━━ 1s 26ms/step

2024-09-26 19:24:12,331 - INFO - Shapes: y_test: (308, 190), y_pred: (308, 1)
2024-09-26 19:24:12,331 - INFO - Types: y_test: <class 'pandas.core.frame.DataFrame'>, y_pred: <class 'numpy.ndarray'>
2024-09-26 19:24:12,346 - INFO - Model for feature 'vbur_near_vtot_boltz' evaluated. Test MAE: 56.946421683237304, R²: 0.6559575283924448
2024-09-26 19:24:12,449 - WARNING - Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.

model_vbur_near_vtot_delta.h5
vbur_near_vtot_delta
vbur_near_vtot_delta
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step

2024-09-26 19:24:12,794 - INFO - Shapes: y_test: (308, 190), y_pred: (308, 1)
2024-09-26 19:24:12,794 - INFO - Types: y_test: <class 'pandas.core.frame.DataFrame'>, y_pred: <class 'numpy.ndarray'>
2024-09-26 19:24:12,800 - INFO - Model for feature 'vbur_near_vtot_delta' evaluated. Test MAE: 13.689984272445653, R²: 0.5872570784538064

model_vbur_near_vtot_max.h5
vbur_near_vtot_max
vbur_near_vtot_max

2024-09-26 19:24:13,056 - WARNING - Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.

10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 28ms/step

2024-09-26 19:24:13,700 - INFO - Shapes: y_test: (308, 190), y_pred: (308, 1)
2024-09-26 19:24:13,700 - INFO - Types: y_test: <class 'pandas.core.frame.DataFrame'>, y_pred: <class 'numpy.ndarray'>
2024-09-26 19:24:13,716 - INFO - Model for feature 'vbur_near_vtot_max' evaluated. Test MAE: 44.46705559312353, R²: 0.773697880023538
2024-09-26 19:24:13,900 - WARNING - Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.

model_vbur_near_vtot_min.h5
vbur_near_vtot_min
vbur_near_vtot_min
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step

2024-09-26 19:24:14,386 - INFO - Shapes: y_test: (308, 190), y_pred: (308, 1)
2024-09-26 19:24:14,386 - INFO - Types: y_test: <class 'pandas.core.frame.DataFrame'>, y_pred: <class 'numpy.ndarray'>
2024-09-26 19:24:14,386 - INFO - Model for feature 'vbur_near_vtot_min' evaluated. Test MAE: 57.36768503356038, R²: 0.6323617666657924
2024-09-26 19:24:14,533 - WARNING - Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.

model_vbur_near_vtot_vburminconf.h5
vbur_near_vtot_vburminconf
vbur_near_vtot_vburminconf
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step

2024-09-26 19:24:14,927 - INFO - Shapes: y_test: (308, 190), y_pred: (308, 1)
2024-09-26 19:24:14,927 - INFO - Types: y_test: <class 'pandas.core.frame.DataFrame'>, y_pred: <class 'numpy.ndarray'>
2024-09-26 19:24:14,927 - INFO - Model for feature 'vbur_near_vtot_vburminconf' evaluated. Test MAE: 46.58688497942935, R²: 0.7472790827698346

model_vbur_ovbur_max_boltz.h5
vbur_ovbur_max_boltz
vbur_ovbur_max_boltz

2024-09-26 19:24:15,021 - WARNING - Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.

10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step

2024-09-26 19:24:15,333 - INFO - Shapes: y_test: (308, 190), y_pred: (308, 1)
2024-09-26 19:24:15,333 - INFO - Types: y_test: <class 'pandas.core.frame.DataFrame'>, y_pred: <class 'numpy.ndarray'>
2024-09-26 19:24:15,333 - INFO - Model for feature 'vbur_ovbur_max_boltz' evaluated. Test MAE: 1.3078790906606017, R²: 0.693104276115112

model_vbur_ovbur_max_delta.h5
vbur_ovbur_max_delta
vbur_ovbur_max_delta

2024-09-26 19:24:15,483 - WARNING - Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.

10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step

2024-09-26 19:24:15,967 - INFO - Shapes: y_test: (308, 190), y_pred: (308, 1)
2024-09-26 19:24:15,967 - INFO - Types: y_test: <class 'pandas.core.frame.DataFrame'>, y_pred: <class 'numpy.ndarray'>
2024-09-26 19:24:15,970 - INFO - Model for feature 'vbur_ovbur_max_delta' evaluated. Test MAE: 1.2376816024288977, R²: 0.640102705433286
2024-09-26 19:24:16,117 - WARNING - Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.

model_vbur_ovbur_max_max.h5
vbur_ovbur_max_max
vbur_ovbur_max_max
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step

2024-09-26 19:24:16,533 - INFO - Shapes: y_test: (308, 190), y_pred: (308, 1)
2024-09-26 19:24:16,535 - INFO - Types: y_test: <class 'pandas.core.frame.DataFrame'>, y_pred: <class 'numpy.ndarray'>
2024-09-26 19:24:16,537 - INFO - Model for feature 'vbur_ovbur_max_max' evaluated. Test MAE: 1.086336418799399, R²: 0.7798381129186774

model_vbur_ovbur_max_min.h5
vbur_ovbur_max_min
vbur_ovbur_max_min

2024-09-26 19:24:16,742 - WARNING - Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.

10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 24ms/step

2024-09-26 19:24:17,288 - INFO - Shapes: y_test: (308, 190), y_pred: (308, 1)
2024-09-26 19:24:17,288 - INFO - Types: y_test: <class 'pandas.core.frame.DataFrame'>, y_pred: <class 'numpy.ndarray'>
2024-09-26 19:24:17,290 - INFO - Model for feature 'vbur_ovbur_max_min' evaluated. Test MAE: 1.2872150040924404, R²: 0.6775669830388923
2024-09-26 19:24:17,405 - WARNING - Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.

model_vbur_ovbur_max_vburminconf.h5
vbur_ovbur_max_vburminconf
vbur_ovbur_max_vburminconf
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step

2024-09-26 19:24:17,724 - INFO - Shapes: y_test: (308, 190), y_pred: (308, 1)
2024-09-26 19:24:17,725 - INFO - Types: y_test: <class 'pandas.core.frame.DataFrame'>, y_pred: <class 'numpy.ndarray'>
2024-09-26 19:24:17,726 - INFO - Model for feature 'vbur_ovbur_max_vburminconf' evaluated. Test MAE: 1.7004063125208075, R²: 0.4829878611129702

model_vbur_ovbur_min_boltz.h5
vbur_ovbur_min_boltz
vbur_ovbur_min_boltz

2024-09-26 19:24:17,886 - WARNING - Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.

10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step

2024-09-26 19:24:18,320 - INFO - Shapes: y_test: (308, 190), y_pred: (308, 1)
2024-09-26 19:24:18,321 - INFO - Types: y_test: <class 'pandas.core.frame.DataFrame'>, y_pred: <class 'numpy.ndarray'>
2024-09-26 19:24:18,325 - INFO - Model for feature 'vbur_ovbur_min_boltz' evaluated. Test MAE: 0.1751642823443136, R²: -0.033560552146645106

model_vbur_ovbur_min_delta.h5
vbur_ovbur_min_delta
vbur_ovbur_min_delta

2024-09-26 19:24:18,428 - WARNING - Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.

10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step

2024-09-26 19:24:18,767 - INFO - Shapes: y_test: (308, 190), y_pred: (308, 1)
2024-09-26 19:24:18,767 - INFO - Types: y_test: <class 'pandas.core.frame.DataFrame'>, y_pred: <class 'numpy.ndarray'>
2024-09-26 19:24:18,776 - INFO - Model for feature 'vbur_ovbur_min_delta' evaluated. Test MAE: 0.5642018303202871, R²: 0.09924465891516232

model_vbur_ovbur_min_max.h5
vbur_ovbur_min_max
vbur_ovbur_min_max

2024-09-26 19:24:18,883 - WARNING - Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.

10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step

2024-09-26 19:24:19,202 - INFO - Shapes: y_test: (308, 190), y_pred: (308, 1)
2024-09-26 19:24:19,202 - INFO - Types: y_test: <class 'pandas.core.frame.DataFrame'>, y_pred: <class 'numpy.ndarray'>
2024-09-26 19:24:19,204 - INFO - Model for feature 'vbur_ovbur_min_max' evaluated. Test MAE: 0.5951466250727425, R²: 0.14094818830284783

model_vbur_ovbur_min_min.h5
vbur_ovbur_min_min
vbur_ovbur_min_min

2024-09-26 19:24:19,372 - WARNING - Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.

10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step

2024-09-26 19:24:19,777 - INFO - Shapes: y_test: (308, 190), y_pred: (308, 1)
2024-09-26 19:24:19,778 - INFO - Types: y_test: <class 'pandas.core.frame.DataFrame'>, y_pred: <class 'numpy.ndarray'>
2024-09-26 19:24:19,780 - INFO - Model for feature 'vbur_ovbur_min_min' evaluated. Test MAE: 0.22021813348339145, R²: -0.07446186071287064
2024-09-26 19:24:19,916 - WARNING - Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.

model_vbur_ovbur_min_vburminconf.h5
vbur_ovbur_min_vburminconf
vbur_ovbur_min_vburminconf
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step

2024-09-26 19:24:20,279 - INFO - Shapes: y_test: (308, 190), y_pred: (308, 1)
2024-09-26 19:24:20,281 - INFO - Types: y_test: <class 'pandas.core.frame.DataFrame'>, y_pred: <class 'numpy.ndarray'>
2024-09-26 19:24:20,284 - INFO - Model for feature 'vbur_ovbur_min_vburminconf' evaluated. Test MAE: 0.0715376178279965, R²: -0.008444460965842504

model_vbur_ovtot_max_boltz.h5
vbur_ovtot_max_boltz
vbur_ovtot_max_boltz

2024-09-26 19:24:20,389 - WARNING - Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.

10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step

2024-09-26 19:24:20,735 - INFO - Shapes: y_test: (308, 190), y_pred: (308, 1)
2024-09-26 19:24:20,737 - INFO - Types: y_test: <class 'pandas.core.frame.DataFrame'>, y_pred: <class 'numpy.ndarray'>
2024-09-26 19:24:20,739 - INFO - Model for feature 'vbur_ovtot_max_boltz' evaluated. Test MAE: 15.992180821710887, R²: 0.795859706454871

model_vbur_ovtot_max_delta.h5
vbur_ovtot_max_delta
vbur_ovtot_max_delta

2024-09-26 19:24:20,838 - WARNING - Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.

10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step

2024-09-26 19:24:21,182 - INFO - Shapes: y_test: (308, 190), y_pred: (308, 1)
2024-09-26 19:24:21,183 - INFO - Types: y_test: <class 'pandas.core.frame.DataFrame'>, y_pred: <class 'numpy.ndarray'>
2024-09-26 19:24:21,186 - INFO - Model for feature 'vbur_ovtot_max_delta' evaluated. Test MAE: 11.753707411968964, R²: 0.5777567697941658

model_vbur_ovtot_max_max.h5
vbur_ovtot_max_max
vbur_ovtot_max_max

2024-09-26 19:24:21,273 - WARNING - Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.

10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step

2024-09-26 19:24:21,606 - INFO - Shapes: y_test: (308, 190), y_pred: (308, 1)
2024-09-26 19:24:21,607 - INFO - Types: y_test: <class 'pandas.core.frame.DataFrame'>, y_pred: <class 'numpy.ndarray'>
2024-09-26 19:24:21,610 - INFO - Model for feature 'vbur_ovtot_max_max' evaluated. Test MAE: 18.65552783141643, R²: 0.7920802848150182

model_vbur_ovtot_max_min.h5
vbur_ovtot_max_min
vbur_ovtot_max_min

2024-09-26 19:24:21,678 - WARNING - Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.

10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 9ms/step

2024-09-26 19:24:21,941 - INFO - Shapes: y_test: (308, 190), y_pred: (308, 1)
2024-09-26 19:24:21,943 - INFO - Types: y_test: <class 'pandas.core.frame.DataFrame'>, y_pred: <class 'numpy.ndarray'>
2024-09-26 19:24:21,946 - INFO - Model for feature 'vbur_ovtot_max_min' evaluated. Test MAE: 16.908834432459226, R²: 0.7478512433119958

model_vbur_ovtot_max_vburminconf.h5
vbur_ovtot_max_vburminconf
vbur_ovtot_max_vburminconf

2024-09-26 19:24:22,150 - WARNING - Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.

10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 25ms/step

2024-09-26 19:24:22,730 - INFO - Shapes: y_test: (308, 190), y_pred: (308, 1)
2024-09-26 19:24:22,732 - INFO - Types: y_test: <class 'pandas.core.frame.DataFrame'>, y_pred: <class 'numpy.ndarray'>
2024-09-26 19:24:22,734 - INFO - Model for feature 'vbur_ovtot_max_vburminconf' evaluated. Test MAE: 20.509661427686403, R²: 0.7285955097841632
2024-09-26 19:24:22,880 - WARNING - Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.

model_vbur_ovtot_min_boltz.h5
vbur_ovtot_min_boltz
vbur_ovtot_min_boltz
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step

2024-09-26 19:24:23,283 - INFO - Shapes: y_test: (308, 190), y_pred: (308, 1)
2024-09-26 19:24:23,283 - INFO - Types: y_test: <class 'pandas.core.frame.DataFrame'>, y_pred: <class 'numpy.ndarray'>
2024-09-26 19:24:23,283 - INFO - Model for feature 'vbur_ovtot_min_boltz' evaluated. Test MAE: 0.3651572538775424, R²: -0.039574262492157564

model_vbur_ovtot_min_delta.h5
vbur_ovtot_min_delta
vbur_ovtot_min_delta

2024-09-26 19:24:23,477 - WARNING - Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.

10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 21ms/step

2024-09-26 19:24:23,933 - INFO - Shapes: y_test: (308, 190), y_pred: (308, 1)
2024-09-26 19:24:23,934 - INFO - Types: y_test: <class 'pandas.core.frame.DataFrame'>, y_pred: <class 'numpy.ndarray'>
2024-09-26 19:24:23,936 - INFO - Model for feature 'vbur_ovtot_min_delta' evaluated. Test MAE: 1.2038150210159042, R²: -0.024920332941608114
2024-09-26 19:24:24,036 - WARNING - Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.

model_vbur_ovtot_min_max.h5
vbur_ovtot_min_max
vbur_ovtot_min_max
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 19ms/step

2024-09-26 19:24:24,454 - INFO - Shapes: y_test: (308, 190), y_pred: (308, 1)
2024-09-26 19:24:24,454 - INFO - Types: y_test: <class 'pandas.core.frame.DataFrame'>, y_pred: <class 'numpy.ndarray'>
2024-09-26 19:24:24,454 - INFO - Model for feature 'vbur_ovtot_min_max' evaluated. Test MAE: 1.2787745606380603, R²: -0.056292584471414164
2024-09-26 19:24:24,598 - WARNING - Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.

model_vbur_ovtot_min_min.h5
vbur_ovtot_min_min
vbur_ovtot_min_min
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step

2024-09-26 19:24:24,950 - INFO - Shapes: y_test: (308, 190), y_pred: (308, 1)
2024-09-26 19:24:24,950 - INFO - Types: y_test: <class 'pandas.core.frame.DataFrame'>, y_pred: <class 'numpy.ndarray'>
2024-09-26 19:24:24,953 - INFO - Model for feature 'vbur_ovtot_min_min' evaluated. Test MAE: 0.09754772204392358, R²: -0.01030663383886088

model_vbur_ovtot_min_vburminconf.h5
vbur_ovtot_min_vburminconf
vbur_ovtot_min_vburminconf

2024-09-26 19:24:25,082 - WARNING - Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.

10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step

2024-09-26 19:24:25,417 - INFO - Shapes: y_test: (308, 190), y_pred: (308, 1)
2024-09-26 19:24:25,417 - INFO - Types: y_test: <class 'pandas.core.frame.DataFrame'>, y_pred: <class 'numpy.ndarray'>
2024-09-26 19:24:25,420 - INFO - Model for feature 'vbur_ovtot_min_vburminconf' evaluated. Test MAE: 0.2975179181014683, R²: -0.0568738361519292

model_vbur_qvbur_max_boltz.h5
vbur_qvbur_max_boltz
vbur_qvbur_max_boltz

2024-09-26 19:24:25,516 - WARNING - Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.

10/10 ━━━━━━━━━━━━━━━━━━━━ 1s 14ms/step

2024-09-26 19:24:26,709 - INFO - Shapes: y_test: (308, 190), y_pred: (308, 1)
2024-09-26 19:24:26,709 - INFO - Types: y_test: <class 'pandas.core.frame.DataFrame'>, y_pred: <class 'numpy.ndarray'>
2024-09-26 19:24:26,712 - INFO - Model for feature 'vbur_qvbur_max_boltz' evaluated. Test MAE: 2.616706765500864, R²: 0.7984905488267264

model_vbur_qvbur_max_delta.h5
vbur_qvbur_max_delta
vbur_qvbur_max_delta

2024-09-26 19:24:26,832 - WARNING - Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.

10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step

2024-09-26 19:24:27,252 - INFO - Shapes: y_test: (308, 190), y_pred: (308, 1)
2024-09-26 19:24:27,253 - INFO - Types: y_test: <class 'pandas.core.frame.DataFrame'>, y_pred: <class 'numpy.ndarray'>
2024-09-26 19:24:27,256 - INFO - Model for feature 'vbur_qvbur_max_delta' evaluated. Test MAE: 3.440715890167992, R²: 0.6396467111083324

model_vbur_qvbur_max_max.h5
vbur_qvbur_max_max
vbur_qvbur_max_max

2024-09-26 19:24:27,350 - WARNING - Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.

10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step

2024-09-26 19:24:27,653 - INFO - Shapes: y_test: (308, 190), y_pred: (308, 1)
2024-09-26 19:24:27,653 - INFO - Types: y_test: <class 'pandas.core.frame.DataFrame'>, y_pred: <class 'numpy.ndarray'>
2024-09-26 19:24:27,654 - INFO - Model for feature 'vbur_qvbur_max_max' evaluated. Test MAE: 3.4775161209295256, R²: 0.7684723138132658

model_vbur_qvbur_max_min.h5
vbur_qvbur_max_min
vbur_qvbur_max_min

2024-09-26 19:24:27,749 - WARNING - Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.

10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step

2024-09-26 19:24:28,090 - INFO - Shapes: y_test: (308, 190), y_pred: (308, 1)
2024-09-26 19:24:28,090 - INFO - Types: y_test: <class 'pandas.core.frame.DataFrame'>, y_pred: <class 'numpy.ndarray'>
2024-09-26 19:24:28,090 - INFO - Model for feature 'vbur_qvbur_max_min' evaluated. Test MAE: 2.4322453543994063, R²: 0.5154365931308098

model_vbur_qvbur_max_vburminconf.h5
vbur_qvbur_max_vburminconf
vbur_qvbur_max_vburminconf

2024-09-26 19:24:28,215 - WARNING - Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.

10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step

2024-09-26 19:24:28,521 - INFO - Shapes: y_test: (308, 190), y_pred: (308, 1)
2024-09-26 19:24:28,522 - INFO - Types: y_test: <class 'pandas.core.frame.DataFrame'>, y_pred: <class 'numpy.ndarray'>
2024-09-26 19:24:28,522 - INFO - Model for feature 'vbur_qvbur_max_vburminconf' evaluated. Test MAE: 2.4173034452342246, R²: 0.5386454939203373

model_vbur_qvbur_min_boltz.h5
vbur_qvbur_min_boltz
vbur_qvbur_min_boltz

2024-09-26 19:24:28,623 - WARNING - Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.

10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step

2024-09-26 19:24:28,948 - INFO - Shapes: y_test: (308, 190), y_pred: (308, 1)
2024-09-26 19:24:28,949 - INFO - Types: y_test: <class 'pandas.core.frame.DataFrame'>, y_pred: <class 'numpy.ndarray'>
2024-09-26 19:24:28,950 - INFO - Model for feature 'vbur_qvbur_min_boltz' evaluated. Test MAE: 1.0527060886280628, R²: 0.46826826829922885

model_vbur_qvbur_min_delta.h5
vbur_qvbur_min_delta
vbur_qvbur_min_delta

2024-09-26 19:24:29,165 - WARNING - Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.

10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 23ms/step

2024-09-26 19:24:29,669 - INFO - Shapes: y_test: (308, 190), y_pred: (308, 1)
2024-09-26 19:24:29,669 - INFO - Types: y_test: <class 'pandas.core.frame.DataFrame'>, y_pred: <class 'numpy.ndarray'>
2024-09-26 19:24:29,671 - INFO - Model for feature 'vbur_qvbur_min_delta' evaluated. Test MAE: 1.415059350056309, R²: 0.4152388452022837
2024-09-26 19:24:29,762 - WARNING - Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.

model_vbur_qvbur_min_max.h5
vbur_qvbur_min_max
vbur_qvbur_min_max
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step

2024-09-26 19:24:30,114 - INFO - Shapes: y_test: (308, 190), y_pred: (308, 1)
2024-09-26 19:24:30,115 - INFO - Types: y_test: <class 'pandas.core.frame.DataFrame'>, y_pred: <class 'numpy.ndarray'>
2024-09-26 19:24:30,117 - INFO - Model for feature 'vbur_qvbur_min_max' evaluated. Test MAE: 1.693946657906169, R²: 0.44033490721120194
2024-09-26 19:24:30,202 - WARNING - Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.

model_vbur_qvbur_min_min.h5
vbur_qvbur_min_min
vbur_qvbur_min_min
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step

2024-09-26 19:24:30,512 - INFO - Shapes: y_test: (308, 190), y_pred: (308, 1)
2024-09-26 19:24:30,512 - INFO - Types: y_test: <class 'pandas.core.frame.DataFrame'>, y_pred: <class 'numpy.ndarray'>
2024-09-26 19:24:30,512 - INFO - Model for feature 'vbur_qvbur_min_min' evaluated. Test MAE: 0.623979518849936, R²: 0.5406138959251299

model_vbur_qvbur_min_vburminconf.h5
vbur_qvbur_min_vburminconf
vbur_qvbur_min_vburminconf

2024-09-26 19:24:30,641 - WARNING - Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.

10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 15ms/step

2024-09-26 19:24:31,026 - INFO - Shapes: y_test: (308, 190), y_pred: (308, 1)
2024-09-26 19:24:31,026 - INFO - Types: y_test: <class 'pandas.core.frame.DataFrame'>, y_pred: <class 'numpy.ndarray'>
2024-09-26 19:24:31,026 - INFO - Model for feature 'vbur_qvbur_min_vburminconf' evaluated. Test MAE: 0.8455369428189871, R²: 0.3550367420765801

model_vbur_qvtot_max_boltz.h5
vbur_qvtot_max_boltz
vbur_qvtot_max_boltz

2024-09-26 19:24:31,082 - WARNING - Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.

10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 8ms/step

2024-09-26 19:24:31,313 - INFO - Shapes: y_test: (308, 190), y_pred: (308, 1)
2024-09-26 19:24:31,314 - INFO - Types: y_test: <class 'pandas.core.frame.DataFrame'>, y_pred: <class 'numpy.ndarray'>
2024-09-26 19:24:31,317 - INFO - Model for feature 'vbur_qvtot_max_boltz' evaluated. Test MAE: 18.852348406274572, R²: 0.7968477445684007

model_vbur_qvtot_max_delta.h5
vbur_qvtot_max_delta
vbur_qvtot_max_delta

2024-09-26 19:24:31,513 - WARNING - Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.

10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 20ms/step

2024-09-26 19:24:31,998 - INFO - Shapes: y_test: (308, 190), y_pred: (308, 1)
2024-09-26 19:24:31,999 - INFO - Types: y_test: <class 'pandas.core.frame.DataFrame'>, y_pred: <class 'numpy.ndarray'>
2024-09-26 19:24:32,000 - INFO - Model for feature 'vbur_qvtot_max_delta' evaluated. Test MAE: 11.49491050080722, R²: 0.5797844061939111
2024-09-26 19:24:32,142 - WARNING - Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.

model_vbur_qvtot_max_max.h5
vbur_qvtot_max_max
vbur_qvtot_max_max
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step

2024-09-26 19:24:32,482 - INFO - Shapes: y_test: (308, 190), y_pred: (308, 1)
2024-09-26 19:24:32,483 - INFO - Types: y_test: <class 'pandas.core.frame.DataFrame'>, y_pred: <class 'numpy.ndarray'>
2024-09-26 19:24:32,485 - INFO - Model for feature 'vbur_qvtot_max_max' evaluated. Test MAE: 30.470070747763675, R²: 0.7074964676951929
2024-09-26 19:24:32,542 - WARNING - Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.

model_vbur_qvtot_max_min.h5
vbur_qvtot_max_min
vbur_qvtot_max_min
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step

2024-09-26 19:24:32,795 - INFO - Shapes: y_test: (308, 190), y_pred: (308, 1)
2024-09-26 19:24:32,795 - INFO - Types: y_test: <class 'pandas.core.frame.DataFrame'>, y_pred: <class 'numpy.ndarray'>
2024-09-26 19:24:32,795 - INFO - Model for feature 'vbur_qvtot_max_min' evaluated. Test MAE: 17.83884563582161, R²: 0.7625599593033934
2024-09-26 19:24:32,881 - WARNING - Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.

model_vbur_qvtot_max_vburminconf.h5
vbur_qvtot_max_vburminconf
vbur_qvtot_max_vburminconf
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step

2024-09-26 19:24:33,195 - INFO - Shapes: y_test: (308, 190), y_pred: (308, 1)
2024-09-26 19:24:33,195 - INFO - Types: y_test: <class 'pandas.core.frame.DataFrame'>, y_pred: <class 'numpy.ndarray'>
2024-09-26 19:24:33,210 - INFO - Model for feature 'vbur_qvtot_max_vburminconf' evaluated. Test MAE: 18.357900567540906, R²: 0.7650239987088927

model_vbur_qvtot_min_boltz.h5
vbur_qvtot_min_boltz
vbur_qvtot_min_boltz

2024-09-26 19:24:33,362 - WARNING - Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.

10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step

2024-09-26 19:24:33,827 - INFO - Shapes: y_test: (308, 190), y_pred: (308, 1)
2024-09-26 19:24:33,843 - INFO - Types: y_test: <class 'pandas.core.frame.DataFrame'>, y_pred: <class 'numpy.ndarray'>
2024-09-26 19:24:33,843 - INFO - Model for feature 'vbur_qvtot_min_boltz' evaluated. Test MAE: 10.485088102610822, R²: 0.5198063711103138
2024-09-26 19:24:34,024 - WARNING - Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.

model_vbur_qvtot_min_delta.h5
vbur_qvtot_min_delta
vbur_qvtot_min_delta
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step

2024-09-26 19:24:34,378 - INFO - Shapes: y_test: (308, 190), y_pred: (308, 1)
2024-09-26 19:24:34,378 - INFO - Types: y_test: <class 'pandas.core.frame.DataFrame'>, y_pred: <class 'numpy.ndarray'>
2024-09-26 19:24:34,378 - INFO - Model for feature 'vbur_qvtot_min_delta' evaluated. Test MAE: 7.980186565376943, R²: 0.5658388099476164

model_vbur_qvtot_min_max.h5
vbur_qvtot_min_max
vbur_qvtot_min_max

2024-09-26 19:24:34,531 - WARNING - Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.

10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 16ms/step

2024-09-26 19:24:34,931 - INFO - Shapes: y_test: (308, 190), y_pred: (308, 1)
2024-09-26 19:24:34,932 - INFO - Types: y_test: <class 'pandas.core.frame.DataFrame'>, y_pred: <class 'numpy.ndarray'>
2024-09-26 19:24:34,934 - INFO - Model for feature 'vbur_qvtot_min_max' evaluated. Test MAE: 11.38200935764084, R²: 0.527893073784834

model_vbur_qvtot_min_min.h5
vbur_qvtot_min_min
vbur_qvtot_min_min

2024-09-26 19:24:35,121 - WARNING - Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.

10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 18ms/step

2024-09-26 19:24:35,492 - INFO - Shapes: y_test: (308, 190), y_pred: (308, 1)
2024-09-26 19:24:35,508 - INFO - Types: y_test: <class 'pandas.core.frame.DataFrame'>, y_pred: <class 'numpy.ndarray'>
2024-09-26 19:24:35,508 - INFO - Model for feature 'vbur_qvtot_min_min' evaluated. Test MAE: 8.371036582087306, R²: 0.6009195749479866

model_vbur_qvtot_min_vburminconf.h5
vbur_qvtot_min_vburminconf
vbur_qvtot_min_vburminconf

2024-09-26 19:24:35,609 - WARNING - Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.

10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step

2024-09-26 19:24:35,929 - INFO - Shapes: y_test: (308, 190), y_pred: (308, 1)
2024-09-26 19:24:35,929 - INFO - Types: y_test: <class 'pandas.core.frame.DataFrame'>, y_pred: <class 'numpy.ndarray'>
2024-09-26 19:24:35,934 - INFO - Model for feature 'vbur_qvtot_min_vburminconf' evaluated. Test MAE: 14.01763576610138, R²: 0.3492139939518123

model_vbur_ratio_vbur_vtot_boltz.h5
vbur_ratio_vbur_vtot_boltz
vbur_ratio_vbur_vtot_boltz

2024-09-26 19:24:36,018 - WARNING - Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.

10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step

2024-09-26 19:24:36,317 - INFO - Shapes: y_test: (308, 190), y_pred: (308, 1)
2024-09-26 19:24:36,317 - INFO - Types: y_test: <class 'pandas.core.frame.DataFrame'>, y_pred: <class 'numpy.ndarray'>
2024-09-26 19:24:36,317 - INFO - Model for feature 'vbur_ratio_vbur_vtot_boltz' evaluated. Test MAE: 0.027105985953906085, R²: 0.5966004715261485
2024-09-26 19:24:36,415 - WARNING - Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.

model_vbur_vbur_boltz.h5
vbur_vbur_boltz
vbur_vbur_boltz
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step

2024-09-26 19:24:36,719 - INFO - Shapes: y_test: (308, 190), y_pred: (308, 1)
2024-09-26 19:24:36,720 - INFO - Types: y_test: <class 'pandas.core.frame.DataFrame'>, y_pred: <class 'numpy.ndarray'>
2024-09-26 19:24:36,722 - INFO - Model for feature 'vbur_vbur_boltz' evaluated. Test MAE: 6.613067385607657, R²: 0.7245996229007825

model_vbur_vbur_delta.h5
vbur_vbur_delta
vbur_vbur_delta

2024-09-26 19:24:36,814 - WARNING - Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.

10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step

2024-09-26 19:24:37,112 - INFO - Shapes: y_test: (308, 190), y_pred: (308, 1)
2024-09-26 19:24:37,128 - INFO - Types: y_test: <class 'pandas.core.frame.DataFrame'>, y_pred: <class 'numpy.ndarray'>
2024-09-26 19:24:37,133 - INFO - Model for feature 'vbur_vbur_delta' evaluated. Test MAE: 7.409570452136677, R²: 0.626515043803178

model_vbur_vbur_max.h5
vbur_vbur_max
vbur_vbur_max

2024-09-26 19:24:37,333 - WARNING - Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.

10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 22ms/step

2024-09-26 19:24:37,784 - INFO - Shapes: y_test: (308, 190), y_pred: (308, 1)
2024-09-26 19:24:37,785 - INFO - Types: y_test: <class 'pandas.core.frame.DataFrame'>, y_pred: <class 'numpy.ndarray'>
2024-09-26 19:24:37,785 - INFO - Model for feature 'vbur_vbur_max' evaluated. Test MAE: 73.21669940562062, R²: -8.073887567049512
2024-09-26 19:24:37,948 - WARNING - Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.

model_vbur_vbur_min.h5
vbur_vbur_min
vbur_vbur_min
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 14ms/step

2024-09-26 19:24:38,337 - INFO - Shapes: y_test: (308, 190), y_pred: (308, 1)
2024-09-26 19:24:38,337 - INFO - Types: y_test: <class 'pandas.core.frame.DataFrame'>, y_pred: <class 'numpy.ndarray'>
2024-09-26 19:24:38,337 - INFO - Model for feature 'vbur_vbur_min' evaluated. Test MAE: 5.306084113458648, R²: 0.6426126175661164

model_vbur_vbur_vburminconf.h5
vbur_vbur_vburminconf
vbur_vbur_vburminconf

2024-09-26 19:24:38,476 - WARNING - Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.

10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step

2024-09-26 19:24:38,836 - INFO - Shapes: y_test: (308, 190), y_pred: (308, 1)
2024-09-26 19:24:38,836 - INFO - Types: y_test: <class 'pandas.core.frame.DataFrame'>, y_pred: <class 'numpy.ndarray'>
2024-09-26 19:24:38,836 - INFO - Model for feature 'vbur_vbur_vburminconf' evaluated. Test MAE: 4.19533081480678, R²: 0.735950474535781

model_vbur_vtot_boltz.h5
vbur_vtot_boltz
vbur_vtot_boltz

2024-09-26 19:24:38,952 - WARNING - Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.

10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 13ms/step

2024-09-26 19:24:39,249 - INFO - Shapes: y_test: (308, 190), y_pred: (308, 1)
2024-09-26 19:24:39,251 - INFO - Types: y_test: <class 'pandas.core.frame.DataFrame'>, y_pred: <class 'numpy.ndarray'>
2024-09-26 19:24:39,254 - INFO - Model for feature 'vbur_vtot_boltz' evaluated. Test MAE: 43.884652101649564, R²: 0.7793498188833317

model_vmin_r_boltz.h5
vmin_r_boltz
vmin_r_boltz

2024-09-26 19:24:39,370 - WARNING - Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.

10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 12ms/step

2024-09-26 19:24:39,714 - INFO - Shapes: y_test: (308, 190), y_pred: (308, 1)
2024-09-26 19:24:39,714 - INFO - Types: y_test: <class 'pandas.core.frame.DataFrame'>, y_pred: <class 'numpy.ndarray'>
2024-09-26 19:24:39,729 - INFO - Model for feature 'vmin_r_boltz' evaluated. Test MAE: 0.07156357688928322, R²: -0.5536063466095646
2024-09-26 19:24:39,784 - WARNING - Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.

model_vmin_vmin_boltz.h5
vmin_vmin_boltz
vmin_vmin_boltz
10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step

2024-09-26 19:24:40,048 - INFO - Shapes: y_test: (308, 190), y_pred: (308, 1)
2024-09-26 19:24:40,049 - INFO - Types: y_test: <class 'pandas.core.frame.DataFrame'>, y_pred: <class 'numpy.ndarray'>
2024-09-26 19:24:40,052 - INFO - Model for feature 'vmin_vmin_boltz' evaluated. Test MAE: 0.017812559883669032, R²: -1.0488371156915859

model_volume_boltz.h5
volume_boltz
volume_boltz

2024-09-26 19:24:40,162 - WARNING - Compiled the loaded model, but the compiled metrics have yet to be built. `model.compile_metrics` will be empty until you train or evaluate the model.

10/10 ━━━━━━━━━━━━━━━━━━━━ 0s 11ms/step

2024-09-26 19:24:40,460 - INFO - Shapes: y_test: (308, 190), y_pred: (308, 1)
2024-09-26 19:24:40,460 - INFO - Types: y_test: <class 'pandas.core.frame.DataFrame'>, y_pred: <class 'numpy.ndarray'>
2024-09-26 19:24:40,460 - INFO - Model for feature 'volume_boltz' evaluated. Test MAE: 54.15265360157201, R²: 0.7481403998093185
2024-09-26 19:24:40,467 - INFO - Model evaluation metrics saved to 'model_evaluation_metrics.csv'.