In [1]:
import pandas as pd 
import numpy as np 
import matplotlib.pyplot as plt 
import os

In [2]:
top20 = pd.read_csv("Low_yield_ligands_top_20_analysis.csv")
top20 = top20.iloc[:-6]

In [3]:
top20.head(20)

   Value  Rows_Appeared_In
0     13                10
1     14                10
2     15                10
3      8                 9
4      4                 9
5     10                 9
6     17                 9
7     18                 9
8      5                 8

In [4]:
df = pd.read_csv('Low_yield_ligands_final_ligand_updated_with_top_20_count.csv')

In [5]:
df = df.sort_values(by="top_20_count", ascending=False)
df.head(20)

,feature,indices,top_20_count
8,model_nbo_bds_e_min_boltz,"[0, 1, 2, 3, 4, 5, 7, 8, 10, 13, 14, 15, 17, 18]",14
9,model_vbur_ovbur_min_delta,"[1, 2, 3, 4, 5, 7, 8, 10, 13, 14, 15, 16, 17, 18]",14
4,model_nbo_bd_e_max_boltz,"[0, 1, 2, 3, 4, 5, 10, 13, 14, 15, 16, 17, 18]",13
5,model_pyr_alpha_min,"[0, 1, 3, 4, 7, 8, 10, 13, 14, 15, 16, 17, 18]",13
6,model_sterimol_B1_max,"[0, 3, 4, 5, 7, 8, 10, 13, 14, 15, 16, 17, 18]",13
7,model_vbur_qvbur_min_boltz,"[0, 3, 4, 5, 7, 8, 10, 13, 14, 15, 16, 17, 18]",13
1,model_sterimol_B5_min,"[2, 4, 5, 7, 8, 10, 13, 14, 15, 16, 17, 18]",12
2,model_vbur_near_vbur_min,"[3, 4, 5, 7, 8, 10, 13, 14, 15, 16, 17, 18]",12
3,model_vbur_near_vbur_vburminconf,"[3, 4, 5, 7, 8, 10, 13, 14, 15, 16, 17, 18]",12
0,model_dipolemoment_vburminconf,"[8, 13, 14, 15]",4

In [6]:
len(df)

10

In [7]:
threshold = pd.read_csv("Low_yield_ligands_final_sorted_best_thresholds.csv")

In [8]:
ligand = pd.read_csv('Low_yield_ligands_final_ligand_with_index.csv')

In [9]:
ligand.head()

,input,model_E_oxidation_boltz,model_E_reduction_boltz,model_E_solv_cds_boltz,model_E_solv_elstat_boltz,model_E_solv_total_boltz,model_Pint_P_int_boltz,model_Pint_P_max_boltz,model_Pint_P_min_boltz,model_Pint_dP_boltz,...,model_vbur_vbur_max,model_vbur_vbur_min,model_vbur_vbur_vburminconf,model_vbur_vtot_boltz,model_vmin_r_boltz,model_vmin_vmin_boltz,model_volume_boltz,yield,SMILES,index_column
0,0000000000000000000000000000000001000000000001...,0.303620,0.076862,-2.404362,-3.899914,-5.572245,16.438795,26.658260,11.354961,3.364319,...,55.491146,44.365550,44.634552,178.65941,1.829504,-0.053807,215.21457,0,CCP(CC)CC,0
1,0000000000000000000000000000000001000000000001...,0.315292,0.079952,0.100458,-5.185666,-3.445140,15.564138,25.196466,11.504475,3.012862,...,42.227734,42.226490,43.004677,117.04840,1.835588,-0.048619,148.69606,0,CP(C)C,1
2,0000000000000000000000000000000000000000000000...,0.298519,0.066568,-1.781534,-4.142239,-6.172190,17.187168,27.688345,12.257298,3.036557,...,57.019880,43.270283,40.860226,210.79329,1.892139,-0.042421,266.44974,0,[N@@]1(C[N@]2C3)CP3C[N@](C2)C1,2
3,0110100000000000000000000000000001000000000001...,0.282032,0.061337,-6.985048,-3.539417,-10.239269,18.203201,31.063185,11.856228,3.557869,...,78.151146,53.715330,52.901450,297.37643,1.795672,-0.059711,341.08774,0,CC(CCC)P(C1CCCCC1)C2CCCCC2,3
4,0000000000000000000000000000000001001000000001...,0.267603,0.056862,-9.630296,-4.263012,-13.797570,19.652014,31.407488,11.884287,3.658416,...,73.715370,58.651604,58.704190,395.04953,1.783544,-0.066182,493.20935,0,CCCCP([C@]1(C[C@H]2C3)C[C@@H](C2)C[C@@H]3C1)[C...,4

In [10]:
new_ligand = ligand.copy()

In [11]:
df1 = top20

df2 = new_ligand
values_to_remove = df1['Value'].unique()

df2_filtered = df2[~df2['index_column'].isin(values_to_remove)]
df2_filtered.head()
# Save the filtered df2 to a new CSV
#df2_filtered.to_csv('filtered_second.csv', index=False)

,input,model_E_oxidation_boltz,model_E_reduction_boltz,model_E_solv_cds_boltz,model_E_solv_elstat_boltz,model_E_solv_total_boltz,model_Pint_P_int_boltz,model_Pint_P_max_boltz,model_Pint_P_min_boltz,model_Pint_dP_boltz,...,model_vbur_vbur_max,model_vbur_vbur_min,model_vbur_vbur_vburminconf,model_vbur_vtot_boltz,model_vmin_r_boltz,model_vmin_vmin_boltz,model_volume_boltz,yield,SMILES,index_column
0,0000000000000000000000000000000001000000000001...,0.303620,0.076862,-2.404362,-3.899914,-5.572245,16.438795,26.658260,11.354961,3.364319,...,55.491146,44.365550,44.634552,178.65941,1.829504,-0.053807,215.21457,0,CCP(CC)CC,0
1,0000000000000000000000000000000001000000000001...,0.315292,0.079952,0.100458,-5.185666,-3.445140,15.564138,25.196466,11.504475,3.012862,...,42.227734,42.226490,43.004677,117.04840,1.835588,-0.048619,148.69606,0,CP(C)C,1
2,0000000000000000000000000000000000000000000000...,0.298519,0.066568,-1.781534,-4.142239,-6.172190,17.187168,27.688345,12.257298,3.036557,...,57.019880,43.270283,40.860226,210.79329,1.892139,-0.042421,266.44974,0,[N@@]1(C[N@]2C3)CP3C[N@](C2)C1,2
3,0110100000000000000000000000000001000000000001...,0.282032,0.061337,-6.985048,-3.539417,-10.239269,18.203201,31.063185,11.856228,3.557869,...,78.151146,53.715330,52.901450,297.37643,1.795672,-0.059711,341.08774,0,CC(CCC)P(C1CCCCC1)C2CCCCC2,3
6,0000000000000000000000000000000000000000000001...,0.272209,0.007912,-7.358131,-7.707565,-14.774627,19.608450,34.806240,13.148209,4.072675,...,49.432610,49.831330,50.169540,323.16733,1.863784,-0.044822,364.83908,5,P(C1=CC=CC=C1)(C2=CC=CC=C2)C3=CC=CC=C3,6

In [12]:
len(df2_filtered)

28

In [13]:
df2_filtered.to_csv('Low_yield_ligands_final_ligand_final_ligands.csv', index=False)

In [14]:
df2_filtered.head()

,input,model_E_oxidation_boltz,model_E_reduction_boltz,model_E_solv_cds_boltz,model_E_solv_elstat_boltz,model_E_solv_total_boltz,model_Pint_P_int_boltz,model_Pint_P_max_boltz,model_Pint_P_min_boltz,model_Pint_dP_boltz,...,model_vbur_vbur_max,model_vbur_vbur_min,model_vbur_vbur_vburminconf,model_vbur_vtot_boltz,model_vmin_r_boltz,model_vmin_vmin_boltz,model_volume_boltz,yield,SMILES,index_column
0,0000000000000000000000000000000001000000000001...,0.303620,0.076862,-2.404362,-3.899914,-5.572245,16.438795,26.658260,11.354961,3.364319,...,55.491146,44.365550,44.634552,178.65941,1.829504,-0.053807,215.21457,0,CCP(CC)CC,0
1,0000000000000000000000000000000001000000000001...,0.315292,0.079952,0.100458,-5.185666,-3.445140,15.564138,25.196466,11.504475,3.012862,...,42.227734,42.226490,43.004677,117.04840,1.835588,-0.048619,148.69606,0,CP(C)C,1
2,0000000000000000000000000000000000000000000000...,0.298519,0.066568,-1.781534,-4.142239,-6.172190,17.187168,27.688345,12.257298,3.036557,...,57.019880,43.270283,40.860226,210.79329,1.892139,-0.042421,266.44974,0,[N@@]1(C[N@]2C3)CP3C[N@](C2)C1,2
3,0110100000000000000000000000000001000000000001...,0.282032,0.061337,-6.985048,-3.539417,-10.239269,18.203201,31.063185,11.856228,3.557869,...,78.151146,53.715330,52.901450,297.37643,1.795672,-0.059711,341.08774,0,CC(CCC)P(C1CCCCC1)C2CCCCC2,3
6,0000000000000000000000000000000000000000000001...,0.272209,0.007912,-7.358131,-7.707565,-14.774627,19.608450,34.806240,13.148209,4.072675,...,49.432610,49.831330,50.169540,323.16733,1.863784,-0.044822,364.83908,5,P(C1=CC=CC=C1)(C2=CC=CC=C2)C3=CC=CC=C3,6

In [15]:
smile = df2_filtered['SMILES']

In [16]:
df2_filtered = df2_filtered.drop(columns=['input', 'SMILES'])

In [17]:
df2_filtered = df2_filtered.drop(df2_filtered.columns[0], axis=1)

df2_filtered['yield'] = pd.to_numeric(df2_filtered['yield'], errors='coerce') 
df2_filtered = df2_filtered.apply(pd.to_numeric, errors='coerce')  

# Drop rows with NaN values (if necessary, or handle them appropriately)
df2_filtered = df2_filtered.dropna()  # Or you could use df.fillna() to replace NaN with a value

best_thresholds = []

# Calculate the total non-zero and zero yields in the dataset
total_non_zero_yields = (df2_filtered['yield'] > 0).sum()
total_zero_yields = (df2_filtered['yield'] == 0).sum()

# Loop through each feature
for feature in df2_filtered.columns:
    if feature != 'yield':  # Skip the target column
        min_val = df2_filtered[feature].min()
        max_val = df2_filtered[feature].max()
        
        thresholds = np.linspace(min_val, max_val, num=500)
        
        best_threshold = None
        max_separation = 0
        best_non_zero_before = 0
        best_zero_before = 0
        best_non_zero_after = 0
        best_zero_after = 0
        best_percent_non_zero_after = 0
        best_percent_zero_after = 0
        
        # Loop through all potential thresholds
        for threshold in thresholds:
            # Split the data into two parts: below and above the threshold
            before = df2_filtered[df2_filtered[feature] < threshold]
            after = df2_filtered[df2_filtered[feature] >= threshold]
            
            # Count non-zero and zero yields in both parts
            zero_before = (before['yield'] == 0).sum()
            non_zero_before = (before['yield'] > 0).sum()
            zero_after = (after['yield'] == 0).sum()
            non_zero_after = (after['yield'] > 0).sum()
            
            # Calculate the absolute difference in non-zero and zero yields on both sides
            separation_before = abs(non_zero_before - zero_before)
            separation_after = abs(non_zero_after - zero_after)
            
            # Calculate the percent of non-zero and zero yields after the threshold relative to total non-zero and zero yields
            percent_non_zero_after = (non_zero_after / total_non_zero_yields) * 100 if total_non_zero_yields > 0 else 0
            percent_zero_after = (zero_after / total_zero_yields) * 100 if total_zero_yields > 0 else 0
            
            # Total separation is the sum of separations on both sides
            total_separation = separation_before + separation_after
            
            # Update the best threshold if this separation is greater
            if total_separation > max_separation:
                max_separation = total_separation
                best_threshold = threshold
                best_non_zero_before = non_zero_before
                best_zero_before = zero_before
                best_non_zero_after = non_zero_after
                best_zero_after = zero_after
                best_percent_non_zero_after = percent_non_zero_after
                best_percent_zero_after = percent_zero_after
        
        # Store the results for this feature
        best_thresholds.append({
            'feature': feature,
            'best_threshold': best_threshold,
            'non_zero_before': best_non_zero_before,
            'zero_before': best_zero_before,
            'non_zero_after': best_non_zero_after,
            'zero_after': best_zero_after,
            'max_separation': max_separation,
            'percent_non_zero_after': best_percent_non_zero_after,
            'percent_zero_after': best_percent_zero_after
        })

# Convert results into a DataFrame for easier viewing
final_updated_best_thresholds_df = pd.DataFrame(best_thresholds)

In [18]:
final_updated_best_thresholds_df = final_updated_best_thresholds_df.sort_values(by=['percent_non_zero_after','percent_zero_after'], ascending=[False, True])

final_updated_best_thresholds_df.head()

,feature,best_threshold,non_zero_before,zero_before,non_zero_after,zero_after,max_separation,percent_non_zero_after,percent_zero_after
12,model_dipolemoment_vburminconf,1.396820,0,6,22,0,28,100.0,0.000000
101,model_sterimol_burB5_min,5.801566,0,5,22,1,26,100.0,16.666667
4,model_Pint_P_int_boltz,18.207003,0,4,22,2,24,100.0,33.333333
5,model_Pint_P_max_boltz,31.085493,0,4,22,2,24,100.0,33.333333
6,model_Pint_P_min_boltz,12.259934,0,4,22,2,24,100.0,33.333333

In [19]:
final_updated_best_thresholds_df.head(20)

,feature,best_threshold,non_zero_before,zero_before,non_zero_after,zero_after,max_separation,percent_non_zero_after,percent_zero_after
12,model_dipolemoment_vburminconf,1.396820,0,6,22,0,28,100.0,0.000000
101,model_sterimol_burB5_min,5.801566,0,5,22,1,26,100.0,16.666667
4,model_Pint_P_int_boltz,18.207003,0,4,22,2,24,100.0,33.333333
5,model_Pint_P_max_boltz,31.085493,0,4,22,2,24,100.0,33.333333
6,model_Pint_P_min_boltz,12.259934,0,4,22,2,24,100.0,33.333333
7,model_Pint_dP_boltz,3.560883,0,4,22,2,24,100.0,33.333333
13,model_efg_amp_P_boltz,1.741942,0,4,22,2,24,100.0,33.333333
21,model_fmo_omega_boltz,0.024230,0,4,22,2,24,100.0,33.333333
58,model_qpoletens_xx_boltz,2.459200,0,4,22,2,24,100.0,33.333333
62,model_qpoletens_xx_vburminconf,3.284498,0,4,22,2,24,100.0,33.333333
74,model_somo_rc_boltz,-0.432956,0,4,22,2,24,100.0,33.333333
83,model_sterimol_B5_boltz,6.321978,0,4,22,2,24,100.0,33.333333
85,model_sterimol_B5_max,6.452285,0,4,22,2,24,100.0,33.333333
87,model_sterimol_B5_vburminconf,6.230217,0,4,22,2,24,100.0,33.333333
102,model_sterimol_burB5_vburminconf,5.751462,0,4,22,2,24,100.0,33.333333
108,model_surface_area_boltz,298.578810,0,4,22,2,24,100.0,33.333333
134,model_vbur_near_vtot_boltz,262.654505,0,4,22,2,24,100.0,33.333333
136,model_vbur_near_vtot_max,298.212366,0,4,22,2,24,100.0,33.333333
137,model_vbur_near_vtot_min,261.065342,0,4,22,2,24,100.0,33.333333
138,model_vbur_near_vtot_vburminconf,276.722055,0,4,22,2,24,100.0,33.333333

In [20]:
final_updated_best_thresholds_df.to_csv('Low_yield_ligands_final_updated_best_thresholds_df.csv', index=False)

In [21]:
df2_filtered.head()

,model_E_reduction_boltz,model_E_solv_cds_boltz,model_E_solv_elstat_boltz,model_E_solv_total_boltz,model_Pint_P_int_boltz,model_Pint_P_max_boltz,model_Pint_P_min_boltz,model_Pint_dP_boltz,model_dipolemoment_boltz,model_dipolemoment_delta,...,model_vbur_vbur_delta,model_vbur_vbur_max,model_vbur_vbur_min,model_vbur_vbur_vburminconf,model_vbur_vtot_boltz,model_vmin_r_boltz,model_vmin_vmin_boltz,model_volume_boltz,yield,index_column
0,0.076862,-2.404362,-3.899914,-5.572245,16.438795,26.658260,11.354961,3.364319,1.462595,0.471522,...,11.970101,55.491146,44.365550,44.634552,178.65941,1.829504,-0.053807,215.21457,0,0
1,0.079952,0.100458,-5.185666,-3.445140,15.564138,25.196466,11.504475,3.012862,1.336064,0.160283,...,3.678765,42.227734,42.226490,43.004677,117.04840,1.835588,-0.048619,148.69606,0,1
2,0.066568,-1.781534,-4.142239,-6.172190,17.187168,27.688345,12.257298,3.036557,1.403691,0.842170,...,11.170786,57.019880,43.270283,40.860226,210.79329,1.892139,-0.042421,266.44974,0,2
3,0.061337,-6.985048,-3.539417,-10.239269,18.203201,31.063185,11.856228,3.557869,0.998266,0.617359,...,24.009241,78.151146,53.715330,52.901450,297.37643,1.795672,-0.059711,341.08774,0,3
6,0.007912,-7.358131,-7.707565,-14.774627,19.608450,34.806240,13.148209,4.072675,1.427522,0.166965,...,0.599956,49.432610,49.831330,50.169540,323.16733,1.863784,-0.044822,364.83908,5,6

In [23]:
import os
import pandas as pd
import matplotlib.pyplot as plt
from matplotlib import font_manager

output_folder = "final_manuscript_plots"
os.makedirs(output_folder, exist_ok=True)

feature_indices = []

for feature in final_updated_best_thresholds_df['feature']:
    
    threshold = final_updated_best_thresholds_df.loc[final_updated_best_thresholds_df['feature'] == feature, 'best_threshold'].values[0]
    feature_column = df2_filtered[feature].values
    yield_column = df2_filtered['yield'].values  
    input_column = smile  
    indices_for_feature = []
    
    for i in range(len(feature_column)):
        if feature_column[i] >= threshold and yield_column[i] == 0:
            indices_for_feature.append(i)  # Store the index of the row
    if indices_for_feature:
        feature_indices.append([feature, indices_for_feature])  # Store feature name and indices
    before_threshold = df2_filtered[feature_column < threshold]
    after_threshold = df2_filtered[feature_column >= threshold]
    
    # Plotting
    plt.figure(figsize=(10, 6))
    plt.scatter(before_threshold[feature], before_threshold['yield'], 
                color='blue', label='Before Threshold', alpha=0.6, edgecolors='k')
    plt.scatter(after_threshold[feature], after_threshold['yield'], 
                color='red', label='After Threshold', alpha=0.6, edgecolors='k')
    
    # Add vertical line for threshold
    plt.axvline(threshold, color='black', linestyle='--', label=f'Threshold = {threshold}')

    # Set title and labels with bold text
    plt.title(f'Scatter Plot of {feature} vs Yield (Threshold = {threshold})', fontweight='bold')
    plt.xlabel(f'{feature} Value', fontweight='bold')
    plt.ylabel('Yield Value', fontweight='bold')
    
    # Set the y-axis to start from -1
    plt.ylim(-3, 100)
    
    # Increase legend font size for clarity
    legend_font = font_manager.FontProperties(weight='bold', size=12)  # Increase font size
    plt.legend(prop=legend_font)
    
    # Add grid for better readability
    plt.grid(True)

    # Save the plot to the folder
    plt.savefig(os.path.join(output_folder, f'{feature}_scatter_plot.png'))
    plt.close()  # Close the plot to avoid display issues

# Create a DataFrame from the list of feature names and indices
final_updated_feature_indices_df = pd.DataFrame(feature_indices, columns=['feature', 'indices'])

# Save the DataFrame to a CSV file (optional)
final_updated_feature_indices_df.to_csv(os.path.join(output_folder, 'final_updated_feature_indices.csv'), index=False)

# Display the DataFrame
print("Feature and corresponding indices DataFrame:")
print(final_updated_feature_indices_df)

Feature and corresponding indices DataFrame:
                      feature          indices
0    model_sterimol_burB5_min              [5]
1      model_Pint_P_int_boltz           [5, 9]
2      model_Pint_P_max_boltz           [5, 9]
3      model_Pint_P_min_boltz           [5, 9]
4         model_Pint_dP_boltz           [5, 9]
..                        ...              ...
174    model_fmo_e_lumo_boltz     [0, 1, 2, 3]
175       model_fmo_eta_boltz     [0, 1, 2, 3]
176        model_fmo_mu_boltz     [0, 1, 2, 3]
177       model_somo_ra_boltz     [0, 1, 2, 3]
178   model_E_reduction_boltz  [0, 1, 2, 3, 9]

[179 rows x 2 columns]

In [23]:
final_updated_feature_indices_df.head()

                    feature indices
0  model_sterimol_burB5_min     [5]
1    model_Pint_P_int_boltz  [5, 9]
2    model_Pint_P_max_boltz  [5, 9]
3    model_Pint_P_min_boltz  [5, 9]
4       model_Pint_dP_boltz  [5, 9]